### ISSUE TITLE
Rails Scrapingの作成について

### ISSUE THREAD

**Issue by ryo-koma** [rexitorg/menta#1]
概要
slackからの続き
rubyで作成したスクレイピングコードをrailsで作成し直す。

https://github.com/ryo-koma/Scraping_rikunabi/invitations

**Comment by ryo-koma** [comment]
> _No description provided._

**Comment by rexitorg** [comment]
@ryo-koma 
こちらPR（Pull Request）の方は内容理解大丈夫でしょうか？
https://github.com/ryo-koma/Scraping_rikunabi/pull/2

**Comment by ryo-koma** [comment]
是非、お願いします！
PRは初めて知りましたが、こちらの内容の理解で合ってますでしょうか？
https://qiita.com/Commander-Aipa/items/d61d21988a36a4d0e58b

**Comment by rexitorg** [comment]
はい！そちらで大丈夫です！:bow:

**Comment by rexitorg** [comment]
すいません。リアクション遅れました:bow: PRの作成方法はそちらで大丈夫ですmm
次は `list_rikunabi_2.rb` をrake taskに置き換えるという変更を行なってPRを作成してみてください:bow:

**Comment by ryo-koma** [comment]
すいません、初歩的な質問ばかりで本当に申し訳ないのですが…
変更するファイルは自分のローカルにあるファイルでいいのでしょうか？
Githubの使い方が全く分からず申し訳ないです。

**Comment by rexitorg** [comment]
全然大丈夫です！気にしないで質問してください！
ローカルのファイルで大丈夫です。

GitHubはクラウドでソースを管理するサービスです。開発フローとしては大まかにいうと

(1) クラウド（GitHub）から最新版のソースをmasterブランチにダウンロードする
=> `git pull` や `git fetch`
その際にローカルブランチが何になっているか確認しておいたほうが良いです。
`git branch -a` で確認できます
master出ない場合は `git checkout master` で masterブランチに切り替えてください。

(2) 開発用のブランチを切り出す
=> `git checkout -b [任意の開発ブランチ名]`
今回だと `git checkout -b feature/refine-scraping-list-2` とかが良いかなと思います。

(3) 修正を行います。

(4) GitHubにブランチの変更をpush（アップロード）します
=> `git push origin HEAD`

(5) GitHub上でレビューしてもらいます。

(6) レビューがおkだった場合にGitHub上のmasterブランチにmergeします。

(7) mergeしたGitHub上の最新masterの変更をローカルブランチを切り替えてpullします。

こちらのサイトが有名なので見てみてください！
https://backlog.com/ja/git-tutorial/

**Comment by rexitorg** [comment]
👍

**Comment by ryo-koma** [comment]
サルでもでtutorialして、repositoriesmからダウンロードしてブランチを切り替えるところまでやりました。ダウンロードしたファイルが先日、コメントしていただく前の内容だったのですが、これはダウンロードしたものが間違っているのでしょうか。
ここのclone or downloadのURLからやりました。
https://github.com/ryo-koma/Scraping_rikunabi

**Comment by rexitorg** [comment]
> ダウンロードしたファイルが先日、コメントしていただく前の内容だったのですが、これはダウンロードしたものが間違っているのでしょうか。
ここのclone or downloadのURLからやりました。

これはGitHubのmasterブランチからpullしているからだと思います。
変更を入れているものは `f/refine-company` というremoteブランチにあるので
`git checkout -t origin/f/refine-company` とするとremoteブランチをローカルブランチにチェックアウトすることができます！

**Comment by ryo-koma** [comment]
ダウンロード出来ました！
rake taskにrikunabi_2を置き換えてpushしようとしてるんですが、エラーが出てしまいます。
調べて対処しようとしてみたもののpushが出来ません。
お時間ある時にご確認いただけますでしょうか。
![image](https://user-images.githubusercontent.com/46399302/51118753-76be1900-1854-11e9-96fc-eb86be096909.png)

**Comment by rexitorg** [comment]
帰宅したら回答します！

**Comment by rexitorg** [comment]
こちら一度 `git pull` してもらえますでしょうか？
https://www.softel.co.jp/blogs/tech/archives/3569
最新の変更が反映されていない可能性があります。

それと今回作業用のbranchは別で切り出して頂きたいです:bow:
`git checkout -b f/[任意の名前]` で作業用ブランチを切り出すことができます！

push するときは `git push origin HEAD` で現在のブランチの最新の変更をremoteブランチにpushできます:bow:

**Comment by ryo-koma** [comment]
出来ました！
rake taskのご確認お願いします。

**Comment by ryo-koma** [comment]
![image](https://user-images.githubusercontent.com/46399302/51227544-3bc4fe00-1998-11e9-9ce9-8bd4ef44f033.png)
こういう風になるのですが、やり方間違えてますでしょうか…？

**Comment by rexitorg** [comment]
> こういう風になるのですが、やり方間違えてますでしょうか…？

これは変更がないってことですね `There isn't anything to compare`なので

`git commit` は完了済みでしょうか？変更したファイルをstagingしてから`git commit`するという作業が必要になります！
commitは変更を確定するという意味合いの作業です:bow:
https://techacademy.jp/magazine/10172

**Comment by ryo-koma** [comment]
![image](https://user-images.githubusercontent.com/46399302/51248267-ece88a00-19d2-11e9-8560-a1c3a155958b.png)

たぶん出来た気がす気がするんですが…いかがでしょうか。

**Comment by rexitorg** [comment]
おお、バッチリです！
あとタイトルとDescriptionのところを詳細化すると非常に良いと思います！
試しに自分の方で簡単に記載してみました！
こちらのPRをベースにレビュー（コードが本当に反映して良いものか判断や修正コメントを入れる作業）を進めることができます。
一旦自分の方でレビューしてみます:bow:

**Comment by rexitorg** [comment]
いえいえ:bow: むしろ細かくてすみませんorz ただ慣れると安全に良い開発が開発できるようになると思います！
レビューしてみました:bow: コメント内容がわからない場合はPRの方にreplyする形でコメントしてください:bow:
また修正できそうな箇所があれば修正commitを積んでpushしてください:bow:
https://github.com/ryo-koma/Scraping_rikunabi/pull/3

**Comment by rexitorg** [comment]
@ryo-koma 
回答しましたー:bow: ご確認頂けましたらこちらの方にもコメントよろしくお願いします。（そのほうが通知がくるので早く気づけます:bow:

**Comment by ryo-koma** [comment]
失礼しましたm( _ _ )m
再度、PRに戻したんですがよろしいでしょうか？

**Comment by rexitorg** [comment]
@ryo-koma 
ありがとうございます！
はい、revertというのは変更前の状態を取り込んで変更をなかったことにするという作業になるのでそれで大丈夫です！

https://github.com/ryo-koma/Scraping_rikunabi/pull/4

LGTM（レビューokのこと）しておいたので一旦masterにmergeしてもらえればと思います:bow:
そしてまたPRを作成してもらえればと思いますmm

**Comment by rexitorg** [comment]
@ryo-koma 
こちら状況いかがでしょうか？次にやることが不明であれば明示しますのでおっしゃってください:bow:
