### ISSUE TITLE
ヘロクでの公開

### ISSUE THREAD

**Issue by takeshikubota** [rexitorg/menta#10]
# 概要
ヘロクでの公開について。
ローカルからリポジトリへのpushでエラー

# 実現したいこと
ヘロクにpushを行いたい

# 困っていること
リポジトリーへのpushでエラーが発生する

# 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to idobata.
remote: 
To https://git.heroku.com/idobata.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/idobata.git'
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ 

# 解決するために行ったこと
・git config --bool core.bare true
・git pull
.envファイルの削除
・config > application.rbに
config.assets.initialize_on_precompile = falseを追加
・エラーの前に追加した「/carrierwave.rb」ファイルを削除

# 問題となっている箇所の予想
いろいろ試して現在、考えられる個所が思い浮かばない状態です。

**Comment by rexitorg** [comment]
dbってpostgreSQLでしたよね？
こちらはいかがでしょうか？
https://kirohi.com/ruby-on-rails%E3%81%AE%E3%82%A2%E3%83%97%E3%83%AA%E3%82%92heroku%E3%81%AB%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E3%81%99%E3%82%8B%E3%81%A8%E3%81%8D%E3%81%AB%E5%87%BA%E3%81%A6%E3%81%8F%E3%82%8B%E3%82%A8

**Comment by takeshikubota** [comment]
ありがとうございます。
こちらは初期に行い問題ないです。一度つながったのですが
heroku関連は対象外でしたでしょうか。

dbはpostgreSQLになります。
リンクの内容は行いました。
2019-01-22T09:54:31.658503+00:00 app[web.1]: from bin/rails:9:in `require'
2019-01-22T09:54:31.658838+00:00 app[web.1]: from bin/rails:9:in `<main>'
2019-01-22T09:54:31.664610+00:00 app[web.1]: => Booting Puma
2019-01-22T09:54:31.664614+00:00 app[web.1]: => Rails 5.1.6.1 application starting in production
2019-01-22T09:54:31.664616+00:00 app[web.1]: => Run `rails server -h` for more startup options
2019-01-22T09:54:31.664618+00:00 app[web.1]: Exiting
2019-01-22T09:54:34.475976+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=idobata.herokuapp.com request_id=55316d26-b75d-4c05-aa6b-aa2bc89b90ae fwd="36.12.3.89" dyno= connect= service= status=503 bytes= protocol=https

**Comment by rexitorg** [comment]
heroku関連も大丈夫です。
リンクの内容を行なって結果どうなりましたか？エラー内容は解消されたかもしくは他のエラーが出るようになったなどありますでしょうか？
あと未解決のissueはcloseしないで頂きたいです:bow:

**Comment by takeshikubota** [comment]
ありがとうございます。
リンクの内容は初期に実施済みです。

AWSにファイルストレージを移行するために試行錯誤してる際に、
下記のエラーが出ました。

closeはDoneの事でしょうか。
この処理実態やり方がわからないのでcloseにした覚えがないです。

require' 2019-01-22T09:54:31.658838+00:00 app[web.1]: from bin/rails:9:in

'
2019-01-22T09:54:31.664610+00:00 app[web.1]: => Booting Puma
2019-01-22T09:54:31.664614+00:00 app[web.1]: => Rails 5.1.6.1 application starting in production
2019-01-22T09:54:31.664616+00:00 app[web.1]: => Run rails server -h for more startup options
2019-01-22T09:54:31.664618+00:00 app[web.1]: Exiting
2019-01-22T09:54:34.475976+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=idobata.herokuapp.com request_id=55316d26-b75d-4c05-aa6b-aa2bc89b90ae fwd="36.12.3.89" dyno= connect= service= status=503 bytes= protocol=https

**Comment by takeshikubota** [comment]
Close and commentですね。気をつけます。

**Comment by rexitorg** [comment]
出力ログってこれが全てでしょうか？下記の記事の通りエラーログをgrep（抽出）して頂きたいです:bow:

https://qiita.com/masarusan24/items/77d064147a32169b5449

```
$ heroku logs | grep error
```

**Comment by takeshikubota** [comment]
grep（抽出）後のエラーログは下記になります。

2019-01-23T01kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ heroku logs | grep error
2019-01-23T01:31:45.611021+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=idobata.herokuapp.com request_id=095898be-a4ae-49cd-a21d-be229d838abf fwd="36.12.8.111" dyno= connect= service= status=503 bytes= protocol=https
2019-01-23T01:31:46.583863+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=idobata.herokuapp.com request_id=7208e547-ee08-4019-8140-b0da2875d1f6 fwd="36.12.8.111" dyno= connect= service= status=503 bytes= protocol=https
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$

**Comment by takeshikubota** [comment]
> herokurun rails console
を実施しました。
｀/app/app/uploaders/image_uploader.rb:1:in `<top (required)>': uninitialized constant CarrierWave (NameError)
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ ｀

**Comment by takeshikubota** [comment]
余計な情報でしたらスルーしていただきたいのですが、
その後の対処の流れになります。

＜＜問題＞＞
heroicでのpushができない

①仮説： H10のエラーはappクラッシュ
→対処
config.autoload_paths += Dir[Rails.root.join('app', 'uploaders')]
を実施。状況変わらず
heroku run rails consoleでエラーを再度確かめる。


＜＜問題＞＞
/app/app/uploaders/image_uploader.rb:1:in `<top (required)>': uninitialized constant CarrierWave (NameError)
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ 
のエラーが出たため 

①仮説CarrierWaveに問題がある。
→対処 CarrierWaveの再度インストール


＜＜問題＞＞
状況は変わらず
uninitialized constant CarrierWave (NameError)のエラー

①仮説：carrierwaveのファイルがない？
→対処：carrierwaveのファイルを作成


②仮説：http://euglena1215.hatenablog.jp/entry/2017/01/07/134802
/https://remonote.jp/rails-carrierwave-fog-s3 の問題？
→対処：上記の内容を参考にcarrierwaveファイルに下記を記載
require 'carrierwave/storage/abstract'
require 'carrierwave/storage/file'
require 'carrierwave/storage/fog'
をconfig/initializers/carrierwave.rbに追加
git push heroku masterを実施

＜＜問題＞＞
$ git push heroku masterを実施
すると下記のエラーが発生
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to idobata.
remote: 
To https://git.heroku.com/idobata.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/idobata.git'
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ 


①仮説：Precompiling assets failed.
のコンパイルの前のアセットファイルの問題？
対処→
1.+ config.assets.initialize_on_precompile = falseの追記
2.config.assets.compile = falseの追記
でも解決せず。

②仮説：Push rejected to idobata.
pushの拒否の問題？
対処
→git push heroku masterでマージとプッシュでも解決せず。


③仮説： ! [remote rejected] master -> master (pre-receive hook declined)
の権限の問題？
対処
→http://tkoyama1988.hatenablog.com/entry/2013/12/13/072150
下記を実施
rm -rf .git
git init 
git add .
git commit -m "First commit"
heroku create --stack cedar
git push heroku master
結果としてエラー。
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ heroku create --stack cedar
Creating app... done, ⬢ calm-shore-56813, stack is heroku-18
https://calm-shore-56813.herokuapp.com/ | https://git.heroku.com/calm-shore-56813.git
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ git push heroku master
error: src refspec master does not match any.
error: failed to push some refs to 'https://git.heroku.com/calm-shore-56813.git'
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ 

もう一度実行してまた同じエラーになる。
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to boiling-refuge-56639.
remote: 
To https://git.heroku.com/boiling-refuge-56639.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/boiling-refuge-56639.git'
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ 


④仮説：error: failed to push some refs to のリモートのブランチとの整合性の問題
の為一度ブランチをして新しいブランチとして作り直す
対処→git push origin :branch-nameを実施
参考：https://qiita.com/yoshixj/items/6441ab2cd6bc367e607d

結果エラー
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$ git push origin master
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rexitorg** [comment]
> /app/app/uploaders/image_uploader.rb:1:in `<top (required)>': uninitialized constant CarrierWave (NameError)
kubotamoutsugu-no-MacBook-Pro:craft-git takeshi$

こちらはクラスが正しく読みこまれていないことが原因のようですね

**Comment by rexitorg** [comment]
色々対応されて現状のアプリケーションの設定状態が不明なので自分の方でrails postgresqlの組み合わせでheroku deployできるところまでの手順を整備しますね:bow:

**Comment by takeshikubota** [comment]
申し訳ございません、、
よろしくお願いします。

2019年1月23日(水) 22:59 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
いえいえ、大丈夫です:bow:
こちら整備してみたのでご確認宜しくお願い致します。作業しながらだったので何か抜けているかもしれないです。詰まったら質問お願いします:bow:
https://docbase.io/posts/631412/sharing/f9da6152-718d-489a-b945-f8e70fd9515c

実際にデプロイしたアプリはこちらになります
https://sample-postgresql-app.herokuapp.com/

**Comment by takeshikubota** [comment]
ありがとうございます。
実行した結果になります。
前回と同様のエラーとなりました。

下記の段階でエラーが出ました。（エラー箇所を記載）
$ heroku buildpacks:set https://github.com/bundler/heroku-buildpack-bundler2.git
# もう一度deploy実行
$ git push heroku master

To https://git.heroku.com/idobatab.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/idobatab.git'

**Comment by rexitorg** [comment]
あ、エラーログも記載していただきたいです:bow:

heroku logsとかでエラーが発生した周辺を貼り付けて頂けると助かりますmm
後コードやログをコメントに貼り付ける時はバッククォート３つ ``` でスニペットの前後を囲んで頂けると助かります:bow:
https://qiita.com/Qiita/items/c686397e4a0f4f11683d#code---%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E6%8C%BF%E5%85%A5

**Comment by takeshikubota** [comment]
よろしくお願いします。

```kubotamoutsugu-no-MacBook-Pro:idobatab takeshi$ heroku logs
2019-01-24T02:35:10.503645+00:00 app[api]: Release v1 created by user paperdesign03@gmail.com
2019-01-24T02:35:10.503645+00:00 app[api]: Initial release by user paperdesign03@gmail.com
2019-01-24T02:36:34.000000+00:00 app[api]: Build started by user paperdesign03@gmail.com
2019-01-24T02:37:22.000000+00:00 app[api]: Build failed -- check your build output: https://dashboard.heroku.com/apps/200d1673-a034-4b62-afb1-c8734c9936e0/activity/builds/16c61b1d-3ff4-46e2-87c5-b2bb6645f0a5
2019-01-24T02:40:20.000000+00:00 app[api]: Build started by user paperdesign03@gmail.com
2019-01-24T02:41:47.073522+00:00 app[api]: Starting process with command `rails db:migrate` by user paperdesign03@gmail.com
2019-01-24T02:41:47.770670+00:00 heroku[run.5306]: Awaiting client
2019-01-24T02:41:48.263206+00:00 heroku[run.5306]: Starting process with command `rails db:migrate`
2019-01-24T02:41:53.141968+00:00 heroku[run.5306]: Process exited with status 127 ```

**Comment by rexitorg** [comment]
あれもっと大量に出ないですかね？

`t`オプションをつけてストリーミング出力にしてエラーが発生する操作を行ってその間に出力されたログを全て貼り付けて欲しいです:bow: お手数おかけしてすみません:pray:
https://qiita.com/pugiemonn/items/c4077958b480eb29878d

**Comment by takeshikubota** [comment]
下記だけでした。。

｀｀｀kubotamoutsugu-no-MacBook-Pro:idobatab takeshi$ heroku logs -t
2019-01-24T02:35:10.503645+00:00 app[api]: Release v1 created by user paperdesign03@gmail.com
2019-01-24T02:35:10.503645+00:00 app[api]: Initial release by user paperdesign03@gmail.com
2019-01-24T02:36:34.000000+00:00 app[api]: Build started by user paperdesign03@gmail.com
2019-01-24T02:37:22.000000+00:00 app[api]: Build failed -- check your build output: https://dashboard.heroku.com/apps/200d1673-a034-4b62-afb1-c8734c9936e0/activity/builds/16c61b1d-3ff4-46e2-87c5-b2bb6645f0a5
2019-01-24T02:40:20.000000+00:00 app[api]: Build started by user paperdesign03@gmail.com
2019-01-24T02:41:47.073522+00:00 app[api]: Starting process with command `rails db:migrate` by user paperdesign03@gmail.com
2019-01-24T02:41:47.770670+00:00 heroku[run.5306]: Awaiting client
2019-01-24T02:41:48.263206+00:00 heroku[run.5306]: Starting process with command `rails db:migrate`
2019-01-24T02:41:53.141968+00:00 heroku[run.5306]: Process exited with status 127｀｀｀

**Comment by takeshikubota** [comment]
お手数をおかけします！
先ほどアカウント追加を行いました。

よろしくお願いします。

2019年1月25日(金) 14:40 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
ありがとうございます！
こちらはもう試されましたか？
https://qiita.com/hiropy0123/items/9e29b2440019fcd9b929

**Comment by majortk** [comment]
k

**Comment by rexitorg** [comment]
こちら確認します:bow: 
今GitHubのmasterに上がっているものは最新のエラーになるソースコードということで良いでしょうか？
自分の手元でも事象が再現するか試して見たいと思います:bow:

**Comment by rexitorg** [comment]
ありがとうございます:bow: 時間がかかってしまい申し訳ありません。今から調査して見ます:bow: 少々お待ちくださいmm

**Comment by rexitorg** [comment]
今日結構時間かけてやってみて最初のエラーは解消したのですが、別のエラーにはまってしまい解消できませんでした。明日もう一度carrierwaveの実装だけ新規アプリを作成してやってみて検証したいと思います:bow:

```
!     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
			Detected buildpacks: Ruby,Node.js
			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.5.3
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.17.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/.........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Fetching rake 12.3.2
       Fetching concurrent-ruby 1.1.4
       Fetching minitest 5.11.3
       Installing minitest 5.11.3
       Installing rake 12.3.2
       Installing concurrent-ruby 1.1.4
       Fetching thread_safe 0.3.6
       Installing thread_safe 0.3.6
       Fetching builder 3.2.3
       Installing builder 3.2.3
       Fetching erubi 1.8.0
       Installing erubi 1.8.0
       Fetching mini_portile2 2.4.0
       Fetching crass 1.0.4
       Installing mini_portile2 2.4.0
       Installing crass 1.0.4
       Fetching rack 2.0.6
       Installing rack 2.0.6
       Fetching nio4r 2.3.1
       Installing nio4r 2.3.1 with native extensions
       Fetching websocket-extensions 0.1.3
       Installing websocket-extensions 0.1.3
       Fetching mini_mime 1.0.1
       Installing mini_mime 1.0.1
       Fetching arel 8.0.0
       Installing arel 8.0.0
       Fetching execjs 2.7.0
       Installing execjs 2.7.0
       Fetching popper_js 1.14.5
       Fetching rb-fsevent 0.10.3
       Installing popper_js 1.14.5
       Fetching ffi 1.9.25
       Installing rb-fsevent 0.10.3
       Using bundler 1.15.2
       Fetching mime-types-data 3.2018.0812
       Installing ffi 1.9.25 with native extensions
       Installing mime-types-data 3.2018.0812
       Fetching coffee-script-source 1.12.2
       Installing coffee-script-source 1.12.2
       Fetching method_source 0.9.2
       Installing method_source 0.9.2
       Fetching thor 0.20.3
       Installing thor 0.20.3
       Fetching multi_json 1.13.1
       Installing multi_json 1.13.1
       Fetching mini_magick 4.9.2
       Installing mini_magick 4.9.2
       Fetching pg 1.1.3
       Installing pg 1.1.3 with native extensions
       Fetching puma 3.12.0
       Installing puma 3.12.0 with native extensions
       Fetching tilt 2.0.9
       Installing tilt 2.0.9
       Fetching turbolinks-source 5.2.0
       Installing turbolinks-source 5.2.0
       Fetching tzinfo 1.2.5
       Installing tzinfo 1.2.5
       Fetching nokogiri 1.9.1
       Installing nokogiri 1.9.1 with native extensions
       Fetching i18n 1.3.0
       Installing i18n 1.3.0
       Fetching websocket-driver 0.6.5
       Installing websocket-driver 0.6.5 with native extensions
       Fetching mail 2.7.1
       Installing mail 2.7.1
       Fetching rack-test 1.1.0
       Installing rack-test 1.1.0
       Fetching sprockets 3.7.2
       Installing sprockets 3.7.2
       Fetching autoprefixer-rails 9.4.2
       Installing autoprefixer-rails 9.4.2
       Fetching uglifier 4.1.20
       Installing uglifier 4.1.20
       Fetching mime-types 3.2.2
       Installing mime-types 3.2.2
       Fetching coffee-script 2.4.1
       Installing coffee-script 2.4.1
       Fetching turbolinks 5.2.0
       Installing turbolinks 5.2.0
       Fetching rb-inotify 0.10.0
       Installing rb-inotify 0.10.0
       Fetching sassc 2.0.0
       Installing sassc 2.0.0 with native extensions
       Fetching activesupport 5.1.6.1
       Installing activesupport 5.1.6.1
       Fetching sass-listen 4.0.0
       Installing sass-listen 4.0.0
       Fetching loofah 2.2.3
       Installing loofah 2.2.3
       Fetching rails-dom-testing 2.0.3
       Installing rails-dom-testing 2.0.3
       Fetching globalid 0.4.1
       Installing globalid 0.4.1
       Fetching activemodel 5.1.6.1
       Fetching jbuilder 2.8.0
       Installing activemodel 5.1.6.1
       Installing jbuilder 2.8.0
       Fetching sass 3.7.2
       Installing sass 3.7.2
       Fetching rails-html-sanitizer 1.0.4
       Installing rails-html-sanitizer 1.0.4
       Fetching activejob 5.1.6.1
       Installing activejob 5.1.6.1
       Fetching activerecord 5.1.6.1
       Installing activerecord 5.1.6.1
       Fetching carrierwave 1.3.1
       Installing carrierwave 1.3.1
       Fetching actionview 5.1.6.1
       Installing actionview 5.1.6.1
       Fetching bootstrap 4.1.3
       Installing bootstrap 4.1.3
       Fetching actionpack 5.1.6.1
       Installing actionpack 5.1.6.1
       Fetching actionmailer 5.1.6.1
       Fetching actioncable 5.1.6.1
       Installing actioncable 5.1.6.1
       Installing actionmailer 5.1.6.1
       Fetching railties 5.1.6.1
       Fetching sprockets-rails 3.2.1
       Installing railties 5.1.6.1
       Installing sprockets-rails 3.2.1
       Fetching jquery-rails 4.3.3
       Fetching coffee-rails 4.2.2
       Installing coffee-rails 4.2.2
       Fetching rails 5.1.6.1
       Installing jquery-rails 4.3.3
       Installing rails 5.1.6.1
       Fetching sass-rails 5.0.7
       Installing sass-rails 5.0.7
       Fetching font-awesome-sass 5.5.0.1
       Installing font-awesome-sass 5.5.0.1
       Bundle complete! 22 Gemfile dependencies, 66 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from i18n:
       
       HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
       But that may break your application.
       
       Please check your Rails app for 'config.i18n.fallbacks = true'.
       If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
       'config.i18n.fallbacks = [I18n.default_locale]'.
       If not, fallbacks will be broken in your app by I18n 1.1.x.
       
       For more info see:
       https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
       
       Post-install message from sass:
       
       Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
       
       * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
         primary implementation: https://sass-lang.com/install
       
       * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
         sassc gem: https://github.com/sass/sassc-ruby#readme
       
       * For more details, please refer to the Sass blog:
         http://sass.logdown.com/posts/7081811
       
       Bundle completed (158.88s)
       Cleaning up the bundler cache.
-----> Installing node-v10.14.1-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       LoadError: cannot load such file -- fog/aws
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `block in require'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/carrierwave-1.3.1/lib/carrierwave/uploader/configuration.rb:124:in `eager_load_fog'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/carrierwave-1.3.1/lib/carrierwave/uploader/configuration.rb:139:in `fog_credentials='
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/config/initializers/carrierwave.rb:10:in `block in <top (required)>'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/carrierwave-1.3.1/lib/carrierwave/uploader/configuration.rb:161:in `configure'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/carrierwave-1.3.1/lib/carrierwave.rb:14:in `configure'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/config/initializers/carrierwave.rb:5:in `<top (required)>'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:286:in `load'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:286:in `block in load'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:286:in `load'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/engine.rb:655:in `block in load_config_initializer'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:168:in `instrument'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/engine.rb:654:in `load_config_initializer'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/engine.rb:611:in `each'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/initializable.rb:30:in `run'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/initializable.rb:59:in `block in run_initializers'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/initializable.rb:48:in `each'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/initializable.rb:48:in `tsort_each_child'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/initializable.rb:58:in `run_initializers'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/application.rb:353:in `initialize!'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/config/environment.rb:5:in `<top (required)>'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/application.rb:329:in `require'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/application.rb:329:in `require_environment!'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/application.rb:445:in `block in run_tasks_blocks'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build_bb9b889c6d969e1b395e7d31dcc6644e/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by takeshikubota** [comment]
大変申し訳ないです。。
お手数ですが次の検証を一度行っていただいてから、
この問題についてどうするか相談させてもらえたらと思います。



2019年1月28日(月) 1:02 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
了解です:bow:
修正中のものは下記にupしています:bow:
https://github.com/takeshikubota/idobatab/pull/1

**Comment by rexitorg** [comment]
すいません:bow: 本日業務が立て込んでしまいましてこちら明日対応させて頂きたく思います:bow: ご迷惑おかけしますが宜しくお願いいたします。

**Comment by takeshikubota** [comment]
ありがとうございます！
よろしくお願いします。

2019年1月28日(月) 18:58 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
こちら一旦解決しました！
暫定対応でcarrierwave,s3ではなくcloudinaryというCDNサービスを利用する方式を採用しました。
下記が対応したサンプルアプリケーションと参考にした記事のURLです。

### 基本はこちらをお手本にした方が良いですが、ユーザーの情報を入力するところだけRailsのバージョンが新しくて`form_with`というメソッドを使っているのでこちらは今作成しているRailsのバージョンに合わせて`form_for`なりを使うのが良いかなと思います。
https://rails-ambassador.herokuapp.com/tips/HerokuCloudinaryCarrierwave

### こちらも一応参考になるが、`cloudinary.yml`というファイルを設定する箇所で環境変数を使っていないみたいなのでそこは参考にしてはダメです。環境変数は上の記事を参考にしてください。また自分が作成したサンプルアプリも環境変数を使うようにしています。
https://qiita.com/GenTamura84/items/38cf899827bba050a21c

サンプルアプリで主に変更した箇所は下記
https://github.com/rexitorg/cloudinary-rails/pull/1

実際にheroku上にdeployしているアプリケーションは下記
https://cloudinary-rails.herokuapp.com/users/1

また上記の暫定対応をする過程でS3を採用する方式も何が問題だったか予想がつきました。ちょっとこちらは解消することが確認できていないので後日対応とさせてください。
上記のサンプルアプリケーションと記事でcloudinaryでの対応をしてもらえればと思います。
ちょっとcarrierwave.rbとかは削除しないといけないかもなのでめんどくさいかもです。
S3の方も時間があるときに解消するか見て見たいと思います。予想があって入れば多分解消するので。

**Comment by takeshikubota** [comment]
誠にありがとうございます！
大変感謝です。確認します！

2019年1月29日(火) 22:11 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
@takeshikubota 
こちら確認状況いかがでしょうか？

**Comment by takeshikubota** [comment]
一度閉めます
後で参照します。
