### ISSUE TITLE
インターンシップに関しての質問

### ISSUE THREAD

**Issue by RYUTAONO0929** [rexitorg/menta#11]
# 概要
無事投稿できていると良いのですが、、、
インターンの件調べていただき有難うございます。
緊急ではないので、他の方の対応を優先してください。
よろしくお願いします。

# 実現したいこと

# 困っていること

# 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。

# 解決するために行ったこと

# 問題となっている箇所の予想

**Comment by rexitorg** [comment]
調べたり思ったことを書きました



# ここら辺はまず整理した方が良い点

- そもそもなぜFintech,ブロックチェーンなのか？
- 何を学びたいのか？
  - エンジニアリング??
  - ビジネスのドメイン知識??
- 何を目指しているのか？
- 3,5,10年のキャリアプランはどうなっているのか？

# おすすめベンチャー

ここら辺は技術力が高いと思われる企業。調べるなり電話するなりしてインターン募集確認すると良いかも。

[株式会社メタップス](https://metaps.com/ja/)

[会計ソフト freee (フリー) \| 無料から使えるクラウド会計ソフト](https://www.freee.co.jp/?referral=aw_freee&referral=aw_freee&gclid=EAIaIQobChMI54GztO2I4AIVWKSWCh0nHw5xEAAYASAAEgIYT_D_BwE)

[無料家計簿・お金の見える化アプリ│マネーフォワード ME](https://moneyforward.com/)

[株式会社メルペイ](https://jp.merpay.com/)

[LINE Corporation \| ホーム](https://linecorp.com/ja/)

[フォリオ \| テーマで選ぶ、かんたん投資。](https://folio-sec.com/?utm_source=a&utm_medium=google&utm_campaign=lstg&utm_content=1#)

# 勉強会に行ってそこにいるエンジニアにきく

あとは勉強会にいっているFintech系のエンジニアに聞くのも良いかも

[FintechのIT勉強会・セミナー・イベント情報 - TECH PLAY［テックプレイ］](https://techplay.jp/tag/fintech)

**Comment by RYUTAONO0929** [comment]
回答ありがとうございます。
ご指摘いただいた点を整理してみます。

**Comment by rexitorg** [comment]
はいー:bow: こちらはcloseしておきます:bow: また何かあれば新規でissue立ててください:bow:
