### ISSUE TITLE
質問お願いします。

### ISSUE THREAD

**Issue by balangan001** [rexitorg/menta#12]
## 質問１
コードを実行するとプログラムが動く事は理解出来ましたが、
複数のユーザーが同じプログラムを実行する場合、
サーバー側でどのように動いているのか理解出来ていません。
わかりやすいサイトや動画があれば教えて下さい。

##質問2
実際の開発現場で使っている
サイト、システムなどを教えて頂けませんか？

**Comment by rexitorg** [comment]
> 質問1

プロセスやスレッドという単位で処理されます。下記の記事内容を見ると理解が深まるかもしれないです:bow:

https://blog.mosuke.tech/entry/2016/06/04/180122/

https://ja.stackoverflow.com/questions/17813/web%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC-rack%E3%81%A8%E3%81%84%E3%81%A3%E3%81%9F%E4%BB%95%E6%A7%98%E3%82%84%E6%A6%82%E5%BF%B5%E3%81%A8-webrick-unicorn-puma%E3%81%A8%E3%81%84%E3%81%A3%E3%81%9F%E5%AE%9F%E8%A3%85%E3%81%AE%E9%96%A2%E4%BF%82%E3%81%8C%E9%A0%AD%E3%81%AE%E4%B8%AD%E3%81%A7%E7%B5%90%E3%81%B3%E3%81%A4%E3%81%8D%E3%81%BE%E3%81%9B%E3%82%93

http://post.simplie.jp/posts/82

> 質問2

アプリケーションの用途などによって異なってくると思います:bow:
業務系システムだとJavaとかを採用しているケースが多かったりします。一般的なWebアプリケーションだと

```
# 使用言語
Ruby

# Web Application Framework
Ruby on Rails

# Public Cloud
AWS(Amazon web service)

# データベース
Amazon Aurora

# Webサーバー
Nginx
```

といった構成が多いかなと思います。
これとかがわかりやすいかもです。
https://employment.en-japan.com/engineerhub/entry/2018/12/21/130000

**Comment by rexitorg** [comment]
まとまっている良いページがありました
https://employment.en-japan.com/engineerhub/entry/2017/04/07/110000

**Comment by balangan001** [comment]
非常にわかりやすいページありがとうございます。
なんとなく理解出来ました！

**Comment by rexitorg** [comment]
よかったです！一旦こちらは解決したのでcloseしておきます:bow:
