### ISSUE TITLE
Railsアプリをロードバランサーで複数のEC2インスタンスで分散して運用したい

### ISSUE THREAD

**Issue by sslleebb** [rexitorg/menta#13]
## 概要

現在、RailsアプリをNginx、Puma、ELB、Redis（ElastiCache）等の構成でサービスをデプロイすることまでは出来ています（デプロイはCapistrano3で行っています）。

ELBはEC2が1つだけの状態で、ELB→Nginx→Pumaという構成なら動かせています（SSL化もしています）。

これで動くので良いかとも思ったのですが、せっかくELBを使っているのだし、複数インスタンスでロードバランサーを使いたいと思いました（そもそも必要なのかは別議論あると思うのですが・・・）。

https://dev.classmethod.jp/cloud/aws/deployment-to-ec2-instances/
こちらの記事の「ベースインスタンスにデプロイし、インスタンスを再構築する」ということができたら便利だと思い、既存のEC2からAMIを作成→EC2インスタンスを作成（複製）という形で複製しました。

https://aws.amazon.com/jp/getting-started/projects/scalable-wordpress-website/03/
複製で参考にしたのはこちらのAWS公式の記事です。

しかし、これだけでは複製したインスタンスはNginxも立ち上がっていない状態ですし、Pumaも起動していなければ、rbenvも動いておらず、諸々足りない状態で、また一からセットアップを行わなくては行けないような状態です。

## 実現したいこと

ベースとなるインスタンスからスムーズにインスタンス複製→ロードバランサーで運用、する方法があるのか、今後スムーズに運営していく上で、普通はどのようなフローで行うのか知りたいです。

## 困っていること

色々調べたのですが、概要の説明はあっても、すでに動いているRailsアプリのインスタンスを複製してロードバランサーで動かす方法が見当たらず。

現状、複製したインスタンスはまだセットアップしていないので、アクセスするたびに、ロードバランサーが分散して、表示→エラーページ→表示→エラーページ、が繰り返す状態です。

**Comment by rexitorg** [comment]
こちら少し調べてサンプルアプリケーションを作って見て動作確認などして回答します:bow:
回答は土,日くらいになると思います:bow:少々お待ち下さい。

**Comment by rexitorg** [comment]
> 勝手がわからずすごい手間をおかけしていたら申し訳ありません。別の上位プランなどご用意頂けましたらそちらに加入しますのでおっしゃってくださいませ。
よろしくお願いいたします。

上位プランは特に用意してないので現状で大丈夫ですw自分の勉強も兼ねているので今の所は問題ありません:smile: 少々お待ち頂ければと思います:bow:

**Comment by rexitorg** [comment]
@sslleebb 
こちら調べました:bow:

現状のNginx, Puma...といった構成を活かすならElastic Beanstalkというアプリケーションの統合管理サービスがあるのでそちらを利用するのが良さそうです。

[AWSのElastic Beanstalkでナウい構成のWebアプリを構築しよう! - Qiita](https://qiita.com/DeployCat/items/f9f0c03080d9cf6c3cc6)

ただ最近だとコンテナイメージを利用するといった選択肢が増える場合はAWSのFargateというサービスを利用するのが最近のやり方みたいです。

[AWS Fargate ことはじめ - log4ketancho](https://www.ketancho.net/entry/2017/12/15/080000)

フルマネージドコンテナサービスを利用してデプロイフローを構築することができそうです。

Dockerイメージを作成してECRに登録してそれをFargateに設定することでデプロイできるようになるようです。

[AWS ECS/Fargate 操作覚え書き - Qiita](https://qiita.com/asato-san/items/a4bd69a6cd30f795201c)

自分もget startedのサンプルアプリケーションを起動したくらいで具体的なサービスで検証はできてないですが、オートスケーリングするような構成にするのであれば上記のようなサービスを使うことになるかと思います:bow:

**Comment by sslleebb** [comment]
@rexitorg さん

あ、お手すきの際に1点だけお伺いしたく。
裏側を知りたいということで、NginxやPumaをCapistrano経由で自前で実装してきましたが、
Elastic Beanstalkを使う以上はCapistranoは基本的に必要ないという認識で良いでしょうか？

素人質問で恐縮ですがよろしくお願いいたします。

**Comment by rexitorg** [comment]
@sslleebb 

> Elastic Beanstalkを使う以上はCapistranoは基本的に必要ないという認識で良いでしょうか？

はい、こちら必要ないという認識で大丈夫だと思います:bow:
こちらの記事とかが参考になりそうと思いました:bow:
https://qiita.com/yuyasat/items/4d93b4ad4f86a6e13d50

**Comment by sslleebb** [comment]
@rexitorg 
ありがとうございます。
なんとかデプロイできました。

なんどかエラーでましたが、全自動で出来てびっくりしました。。
ありがとうございました！

**Comment by rexitorg** [comment]
良かったです:smile: こちらのissueはcloseしておきます！:smile:
