### ISSUE TITLE
pythonまたはruby

### ISSUE THREAD

**Issue by balangan001** [rexitorg/menta#14]
## 困っていること
Pythonを勉強すべきか
Rubyを勉強するべきか

pythonを勉強するかrubyを勉強するか悩んでいます。

◆現状
if,for,while,loop,引数などのPythonの基礎的な事は学習済みです。

プログラミングを勉強してやりたい事は、
WEBアプリケーションの開発と機械学習を活用した投資なので
Pythonを勉強しておけば、どちらも対応出来るかと思い勉強を始めました。

しかし、Pythonの場合、機械学習の記事は、たくさんあるのですが、
Django、WEBアプリケーションに関しての記事が少ないと感じています。

Rubyは、ruby on rails、WEBアプリケーションに関する記事が圧倒的に多いので
困った時に調べれば、ある程度の回答を得る事が出来ると感じています。
しかしrubyは、機械学習に向いていないという点が気になります。

Pythonを勉強してwebアプリケーション開発、
機械学習による投資が出来るようになるのが理想なのですが、

Rubyでwebアプリケーションを作った後に
pythonによる機械学習を勉強すべきでしょうか？

python,ruby共に文法が似ているので
pythonからのruby、rubyからのpython共に難易度は高く無いと感じていますが、
どのようにお考えでしょうか？

**Comment by rexitorg** [comment]
> WEBアプリケーションの開発と機械学習を活用した投資

最終的に何を作りたいかによるかなと思いました。WebアプリケーションであればRuby,RoRの方がよく使われるので学ぶ必要があります。Pythonも文法などは似てますが覚えるべき知識（プログラミング以外に機械学習のことを覚えないといけない）が異なるのでそちらの学習コストがかかるかなと思います。
一応RubyからもPythonのライブラリを呼び出すPycallというgemがあるのでそちらを活用していくのも手かなと思います。
https://qiita.com/stat/items/a383451e7f824e4c9627

Pythonを自分がやったことないのでなんとも言えない部分もありますが、最終的にアプリケーションを作るならまずはRuby,RoRで良いのではないかと思いました。

**Comment by rexitorg** [comment]
@balangan001 
こちら確認いただけましたらレスお願いします:bow:
