### ISSUE TITLE
Edit.htmlでfileds_forのフォームが表示されない。

### ISSUE THREAD

**Issue by sumura80** [rexitorg/menta#15]
## 概要
Postモデルの中に、infoimgモデルをネストし、view/posts/edit.html.erbから画像を投稿するフォームを表示したい。
以前、extraimgというモデルを実装し、そちらは問題なく機能している為同様に記述した。
infoimgのfields_forで画像を投稿できるフォームを表示したいが、edit.html.erb常にフォームが表示されない。（記述しても）

## 実現したいこと
view/posts/edit.html.erbから画像を投稿するフォームを表示したい。

## 困っていること
fields_forのフォームを記述しても、投稿フォームが表示されない。
下記のように記述下が、何も表示されない。
<%= form.fields_for :infoimgs do |infoimg| %>
しかし、infoimg123など適当なテーブル名を記入すると表示される（画像を投稿してもDBには何も保存されない）

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
edit.html.erbには何もエラーが表示されない。これが、逆に怖い。

## 解決するために行ったこと
pryなどでバグを探したが、特に発見されず。"Edit complete"という編集ボタンを押したが、特に問題なく挙動する。

## 問題となっている箇所の予想
views/posts/edit.html.erbの254行あたり。
```
<div class="form-group">
   <%= form.fields_for :infoimgs do |infoimg| %>
        <%= infoimg.text_field :infoimg_name,class: "form-control" %>
        <%= infoimg.file_field :infoimage,class: "form-control" %>
        <%= infoimg.text_area :infoimg_description,class: "form-control"%>
        <%= infoimg.check_box :_destroy %>
         <%= infoimg.label :_destroy, "remove" %>
    <% end %>
 </div>
```

## 問題となっているアプリケーションのGitHub URL
med_plus_bs4_updated_masterのimageboxブランチ。

https://github.com/sumura80/med_plus_bs4_updated_master/tree/imagebox
![edit_html](https://user-images.githubusercontent.com/17425060/52172764-7d87de00-27b9-11e9-89e4-409b13010582.png)

お手数ですが、ご教示ただけると幸いです。
よろしくお願い致します。:bow:

**Comment by sumura80** [comment]
ありがとうございます！！
こちら、`@post.infoimgs.build`をcontrollerに追加したら表示されました。:star2:
seedでテストデータを事前に登録できるのですね。:sweat_drops:　すみませんでした。
今後データを投入してから質問させていただきます。:bow:

ありがとうございました。

**Comment by rexitorg** [comment]
よかったですー:smile:
https://qiita.com/suzuki_koya/items/5ba132facd9812e2c2ec
seeds.rbとかに追加しておくとコマンド一つでseedデータを投入できるようになります:bow:
