### ISSUE TITLE
Deviseを使っているユーザーにEmailを送る。

### ISSUE THREAD

**Issue by sumura80** [rexitorg/menta#16]
## 概要
Userの登録にDeviseを使用しています。
今回、アクションがあるたびにUserにEmailを送りたいと考えております。
Action mailerでEmailを送ることを検討しております。

## 実現したいこと
下記の３アクション時にメール機能を追加したい。
※Userに届くメール。
1.新規登録時の“Welcome” email
2.Email変更時の“Updated” email

※Userからadmin(自分）に届くメール。
3.問い合わせフォームからemail

## 困っていること
通常のAction mailerを実装する時には、UsersコントローラのcreateアクションにMailerメソッドを追加しているようです。
｀SampleMailer.send_when_create(@user).deliver｀

ですが、Deviseを使用すると、このusersコントローラの"Createアクション"が存在しません。
記事によっては、Userのモデルに"after_create, after_update"などで記述する方法。
またDeviseのRegistrations controllerをoverrideする方法などもありました。

どれも基本的なAction mailerのやり方からずれているので、どのような方法で進めれば良いかわかりません。

お忙しいところ恐れ入りますが、ご教示ただけませんでしょうか？
よろしくお願い致します。

**Comment by sumura80** [comment]
早急なご回答ありがとうございます。
コントローラーのオーバーライドがやっぱり良さそうなんですね。

このように、Deviseを使用して、Welcomeメールといったような流れは、実務では使うことはよくありますか？

**Comment by sumura80** [comment]
Deviseで新規登録者に確認メールを送る機能を実装しております。
実装したのですが、新規登録したにもかかわらずメールが飛んでこない状態で困っております。

今回、下記の方法でコントローラーのアクションをオーバーライドする方法を取りました。
https://github.com/plataformatec/devise#configuring-controllers
1.で```rails g devise:controllers users```のようにcontrollerを作成しました。

2.Tell the router to use this controller:
```devise_for :users, controllers: { sessions: 'users/sessions' }```
この箇所で、エラーが発生しました。こちらは、以前にdeviseでuserを登録しているので不要なのかなと思いました。
![defined_2_routes](https://user-images.githubusercontent.com/17425060/52339625-ff456900-2a50-11e9-9ef3-c6b1748f9bbe.png)



3.Copy the views from `devise/sessions` to `users/sessions`. Since the controller was changed, it won't use the default views located in `devise/sessions`.
これですが、これは新しくViewを作成する必要がありますか？


下記も参考
https://easyramble.com/welcome-mail-with-devise.html


こちらに最新版のアプリをアップしてたので、ご確認いただけませんでしょうか。よろしくお願い致します。:bow::bow:
https://github.com/sumura80/med_plus_bs4_updated_master/pull/5

**Comment by rexitorg** [comment]
> コントローラーのオーバーライドがやっぱり良さそうなんですね。

ケースバイケースだと思います。deviseはカスタムするのが結構大変とよくきくので極力オーバーライドしないほうが良いとは思いますが今回のようなケースくらいなら複雑ではないので大丈夫かなと思います:bow:

> このように、Deviseを使用して、Welcomeメールといったような流れは、実務では使うことはよくありますか？

自分は実務では使ったことないですが、使っているシステムもたくさんありますね。有名どころだとhttps://github.com/Sorcery/sorcery とかでしょうか。

**Comment by rexitorg** [comment]
> 2.Tell the router to use this controller:
`devise_for :users, controllers: { sessions: 'users/sessions' }`
この箇所で、エラーが発生しました。こちらは、以前にdeviseでuserを登録しているので不要なのかなと思いました。

`new_user_session` はすでに定義済みと書いてありますね。`rails routes -g new_user_session` でルーティングが定義されているかどうか見た方が良いと思います。

> 3.Copy the views from `devise/sessions` to `users/sessions`. Since the controller was changed, it won't use the default views located in `devise/sessions`.
これですが、これは新しくViewを作成する必要がありますか？

これはデフォルトで使われていたviewがdevise/sessions配下から今回作成したusersの配下に移ったということなのでcopyするか新しく作る必要があると思います。

**Comment by rexitorg** [comment]
@sumura80 
こちら回答内容okでしょうか？

**Comment by sumura80** [comment]
ご連絡ありがとうございます。
こちら進行中なので、もう少しお待ちいただけませんでしょうか？
よろしくお願い致します。:bow:

**Comment by rexitorg** [comment]
了解ですー問題ありません:smile:ありがとうございます:bow:

**Comment by sumura80** [comment]
ご回答ありがとうございました。:bow:
現在下記のエラーでまだ止まっている状況です。

> 2.Tell the router to use this controller:
> `devise_for :users, controllers: { sessions: 'users/sessions' }`
> この箇所で、エラーが発生しました。こちらは、以前にdeviseでuserを登録しているので不要なのかなと思いました。

>`new_user_session` はすでに定義済みと書いてありますね。`rails routes -g new_user_session`  でルーティングが定義されているかどうか見た方が良いと思います。

今回routeにこの行を確認したところすでに定義済みとなっておりました。

```rails routes -g new_user_session
          Prefix Verb URI Pattern              Controller#Action
new_user_session GET  /users/sign_in(.:format) devise/sessions#new
```

しかしこれは、以前作成したDeviseの`route`であり、現在は`devise/sessions` から `users/session`にviewが移動しております。
下記のように記述すると画像のような`ArgumentError`が発生してしまいます。
```
config/routes.rb

devise_for :users
devise_for :users, controllers: { sessions: 'users/sessions' } 
```
![argumenterror](https://user-images.githubusercontent.com/17425060/52526649-1e692280-2cff-11e9-9e73-15a513e3c355.png)



ダブって記述しているので、エラーになるのは理解できるのですが、一つ目の`devise_for :users`を削除するとサインインなどができなくなります。（エラーがでます）
ですが今回は、二つ目の`route`を使う必要があります。

エラー画面に表示されているRailsガイドも参考にしましたが、わかりにくかったです。:sweat:
https://railsguides.jp/routing.html#%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%AE%E4%BD%9C%E6%88%90%E3%82%92%E5%88%B6%E9%99%90%E3%81%99%E3%82%8B


他のサイトでは、一つ目の`route`を削除すれば良いと書いてありましたが、それではうまくいきませんでした。
https://stackoverflow.com/questions/18016761/rails-4-devise-invalid-route-name-already-in-use
ご教示いただけませんでしょうか？よろしくお願い致します。:cold_sweat:

**Comment by sumura80** [comment]
お疲れ様です。
なんとか質問させていただいたエラーは自走することができました。

現在、Action mailerでメール機能を実装ちゅうです。
内容としては、新規ユーザーがサインアップすると、ユーザーにWelcomeメールが届くといった内容です。

そこで、下記のようなエラーで出てしまっております。
![action_mailer_01](https://user-images.githubusercontent.com/17425060/52533586-4b5a1b80-2d79-11e9-8d54-96de925c742c.png)


/app/mailers/user_mailer.rb
には、下記のように記述したのですが、どこがおかしいかわからない状態です。
ご教示いただけませんでしょうか？よろしくお願い致します。:bow:
```
class UserMailer < ApplicationMailer

  # Subject can be set in your I18n file at config/locales/en.yml
  # with the following lookup:
  #
  #   en.user_mailer.signup_confirmation.subject
  #
  
  def signup_confirmation(user)
  	@user = user
    @greeting = "Hi"

    mail (
       from: 'codetest1980@gmail.com',
       to: @user.email,
       subject: "Sign Up Confirmation"

      )
  end
end
```

**Comment by sumura80** [comment]
@rexitorg 
こちら、create時のエラーが解決致しました。
次は、updateのemail変更時に取りかかりますので、もう少しクローズせずにお待ちいただければと思います。:bow:

**Comment by sumura80** [comment]
@rexitorg
お疲れ様です。

昨日ですが、Action Mailerの`create`が途中までエラー解決できました。
letter_opener_webというgemで送信できるか確認したところ、こちらでは、送信が確認できました。


今回エラーが起きている箇所は、gmailで送る時です。
`create`でエラーが起きてしまっているところです。
```
Net::SMTPAuthenticationError in Users::RegistrationsController#create
530-5.5.1 Authentication Required. Learn more at

def create
  super
  UserMailer.signup_confirmation(@user).deliver
end
# GET /resource/sign_up
# def new
```
![2019-02-11 8 33 11](https://user-images.githubusercontent.com/17425060/52541783-53977280-2ddc-11e9-8890-cd3141e58f38.png)




`binding.pry`デバッグしてみたのですが、paramsは問題なく作成できているようです。

```
Redirected to http://localhost:3000/

From: /Users/code_folder/med_plus_lifeabroad/med_plus_bs4_updated_master/app/controllers/users/registrations_controller.rb @ line 9 Users::RegistrationsController#create:

     6: def create
     7:   super
     8:   binding.pry
 =>  9:   UserMailer.signup_confirmation(@user).deliver
    10: end

[1] pry(#<Users::RegistrationsController>)> @user
=> #<User id: 36, email: "pinetree321@hotmail.co.jp", created_at: "2019-02-10 22:51:53", updated_at: "2019-02-10 22:51:53", username: "susumu", user_image: nil, admin: false, deleted_at: nil>
```


エラーを見ると、createで問題が起きていそうなのですが、
`/controllers/users/regstrations_controller.rb`での記述も問題ないように思えます。

```
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def create
    super
    UserMailer.signup_confirmation(@user).deliver
  end
end
```  

Googleでの２段階認証もしております。
user_nameやpasswordはFigaroのgemを使用し、`config/application.yaml`に記述しています。
config/enviornments/development.rb
```  
  ActionMailer::Base.delivery_method = :smtp
  #config.action_mailer.delivery_method = :letter_opener_web
  ActionMailer::Base.smtp_settings = {
  address: 'smtp.gmail.com',
  domain: 'gmail.com',
  port: 587,
  user_name: ENV['ACTION_MAILER_EMAIL_ADDRESS'],
  password: ENV['ACTION_MAILER_EMAIL_PASSWORD']',
  authentication: 'plain',
  enable_starttls_auto: true
}
```  

おかしそうな場所があれば、おしえていただけませんでしょうか？
よろしくお願い致します。:bow:

**Comment by sumura80** [comment]
@rexitorg 
こちらローカルでupdate時のメールも遅れましたので、クローズさせていただきます。
ありがとうございました。
