### ISSUE TITLE
オススメ書籍2冊 読了後のRails学習進め方について

### ISSUE THREAD

**Issue by shumatsumoto** [rexitorg/menta#18]
## 概要
書籍2冊は読破しまして、
その後どのようにRails学習すすめたら良いか、
参考になる良いサイト等々ありましたらご教示ください、お願いいたしますmm

## 困っていること
オススメ書籍の2冊、とても分かりやすくて良かったです！
（こちらは時折読み返したり等、今後も使っていきます）
それで、まだRubyを学びはじめて3ヶ月ほどでして。
今後どのようにRuby、Railsを学んでいくとよいか、
勉強・参考になるサイトだったりありましたらご教示頂ければと思います。

これまでやったこと）
・ドットインストール
・Progate
・チュートリアル（7〜8章くらいで躓いて挫折。。）
・Railsもくもく会参加
・オススメ書籍2冊読破

**Comment by rexitorg** [comment]
@shumatsumoto san

> オススメ書籍の2冊、とても分かりやすくて良かったです！

良書なので是非活用してください！

> その後どのようにRails学習すすめたら良いか、

他の方にも同様の相談をもらったのでまとめてみました。順にすすめてもらえればと思います:bow:

https://docbase.io/posts/627219/sharing/99008c57-48d7-4c2e-82e1-a1d4190f9258

**Comment by shumatsumoto** [comment]
@rexitorg san
早々にお返事ありがとうございます！！
めちゃ助かりますー(*'▽'*)
順に進めていきます、楽しみやわ♪
