### ISSUE TITLE
モーダルウィンドウを実装したい

### ISSUE THREAD

**Issue by shyuhei-kaneko** [rexitorg/menta#19]
## 概要
現在自作中の勤怠を管理をするアプリケーションを作成中です。
作成にあたり、仕様が存在します。(添付しております。)
仕様書内の「残業申請と承認について」シート内に明記されているイベントでモーダルウィンドウが立ち上がる。という仕様になっています。

[勤怠システムA・仕様書.xlsx](https://github.com/rexitorg/menta/files/2848524/A.xlsx)

## 実現したいこと
仕様に準じたモーダルウィンドウを実装を実現したい

## 困っていること
何を学べば実装実現できるのか分かりません。
当方、初学者です。モーダルウィンドウ？jquery?何を学べば実現できるのかが分かりません。申し訳ありません。

## 解決するために行ったこと
WEB検索にていくつか調べましたが理解が出来ませんでした。
https://logist3.com/rails5-bootstrap-modalwindow/

## 問題となっている箇所の予想
何を調べたら理解できるのかが分かりません。

## 問題となっているアプリケーションのGitHub URL
  https://github.com/shyuhei-kaneko/attendance-system

**Comment by rexitorg** [comment]
こちらを参考に `bootstrap` と `popperjs` というのをgemで追加すれば対応できるのかなと思いました:bow:
https://qiita.com/Kolosek/items/4ee80eb0c6dd0af4b1b7

> 何を学べば実装実現できるのか分かりません。
当方、初学者です。モーダルウィンドウ？jquery?何を学べば実現できるのかが分かりません。申し訳ありません。

RailsだとBootstrapというCSSのライブラリがあるのでそちらを使うと簡単に実装できるみたいですmm
学ぶのはCSSやjQuery, JavaScriptあたりですね。

わからない場合は追加で質問お願いします:bow:
@shyuhei-kaneko

**Comment by shyuhei-kaneko** [comment]
ありがとうございます。まずは手順通りに進めていきます。
