### ISSUE TITLE
cssでのviewのレイアウト調整が上手くいかない

### ISSUE THREAD

**Issue by shyuhei-kaneko** [rexitorg/menta#20]
## 概要
現在自作中の勤怠を管理をするアプリケーションを作成中です。
作成にあたり、仕様が存在します。
show.html のviewを仕様に準じて調整致しました。

## 実現したいこと
viewのtdタグをcssで横幅を調整したい。

## 困っていること
自分なりに調べ、classを定義、cssで横幅を指定したのですが変化しません。
画像添付致します。

## 解決するために行ったこと
WEB検索致しましたが解決にいたりませんでした。

## 問題となっている箇所の予想
不明です。

## 問題となっているアプリケーションのGitHub URL
https://github.com/shyuhei-kaneko/attendance-system/blob/master/app/views/users/show.html.erb#L85

<img width="1440" alt="2019-02-10 14 06 02" src="https://user-images.githubusercontent.com/43919890/52529934-35c80000-2d3f-11e9-9fa1-e45d1bdb678b.png">
<img width="1440" alt="2019-02-10 14 10 28" src="https://user-images.githubusercontent.com/43919890/52529935-35c80000-2d3f-11e9-8e6b-1a6f134133f5.png">
<img width="1440" alt="2019-02-10 14 12 47" src="https://user-images.githubusercontent.com/43919890/52529936-36609680-2d3f-11e9-9271-dc84e1e6641b.png">
<img width="1440" alt="2019-02-10 14 13 14" src="https://user-images.githubusercontent.com/43919890/52529937-36609680-2d3f-11e9-80de-0a51926b89af.png">

**Comment by rexitorg** [comment]
tableタグのwidthを設定すれば良さそうですが反映されないでしょうか？

http://www.koikikukan.com/archives/2012/08/20-005555.php

当たっているcssはChromeなら検証で確認してデバッグすることができます。
https://ferret-plus.com/1880

**Comment by rexitorg** [comment]
@shyuhei-kaneko 
ご確認宜しくお願いします:bow:

**Comment by shyuhei-kaneko** [comment]
お世話になります。
頂いたアドバイスを元に修正したらできました！
定義したclassを変更したら解決に至りました。ありがとうございました。

https://github.com/shyuhei-kaneko/attendance-system/pull/2/commits/1f73c08c8728b9674a99b64c97fe998b66f4414f

**Comment by rexitorg** [comment]
おお！良かったです！:smile:
