### ISSUE TITLE
リアクションのデータ保存

### ISSUE THREAD

**Issue by takeshikubota** [rexitorg/menta#23]
## 概要
スワイプ操作でリアクション（like or dislike）の送信を行う機能
を作っています。post/index.html.erbでユーザー（タイプA）からは
成功しているのですが、ユーザー（タイプB）のスワイプ
posts/match.html.erb結果が保存されないと言う状態です。

## 実現したいこと
リアクションの結果をデーターベースに保存したい。

## 困っていること
posts/match.html.erbでのリアクション結果が保存されない。

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
エラーメッセージはなく、
現状、リアクションの送信は行っているが、
保存されていない状態。

## 問題となっている箇所の予想
reaction_post_controllerでのcreateアクション

def create
reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: @current_post.id)
reaction.update_attributes(
status: params[:reaction]
)
end

何度か出ていたエラーは解決したため、
現状仮説がなくなった状態です。。

## 問題となっているアプリケーションのGitHub URL
https://github.com/takeshikubota/hotel

**Comment by rexitorg** [comment]
コードみて思ったこと記載していきます:bow:

**Comment by rexitorg** [comment]
こんな感じでアクションごとにコントローラーきるというのは普通やらないですね。
https://github.com/takeshikubota/hotel/blob/master/app/controllers/reactions_post_controller.rb

postsというリソースにひもづくアクションなのであればposts_controllerの方に`def reaction`というアクションを処理するメソッドを生やすべきだと思います:bow:

**Comment by rexitorg** [comment]
問題となっている箇所ですが以下の観点で`binding.pry` などを使い確認してみてください:bow:

- [ ] `params[:user_id]` に何が格納されているか？
- [ ] `current_post.id` に何が格納されているか？
- [ ] Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: @current_post.id) でリソースはfind（取得）されているのかinitialize（初期化）されているのか？
- [ ] reactionは@reactionをつけてインスタンス変数にする方が良い？
- [ ] reaction_postコントローラーにひもづくviewだとhttps://github.com/takeshikubota/hotel/blob/master/app/views/reactions_post/create.html.erbを表示するようになっているがそれは正しい？

```rb
class ReactionsPostController < ApplicationController
  def create
    reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: @current_post.id)
    reaction.update_attributes(
        status: params[:reaction]
    )
  end
end
```

最後の項目が特に原因になっている気がします。

**Comment by rexitorg** [comment]
@takeshikubota 
ご確認宜しくお願いします:bow:

**Comment by takeshikubota** [comment]
ありがとうございます！やってみます。

**Comment by takeshikubota** [comment]
ありがとうございます。
status: params[:reaction]を調べたのですが。
問題なくリアクションとIDを取っていました。
そしてなぜかデータ保存がその後出来ました。。

理由は今確かめています。完了にします。
