### ISSUE TITLE
チャットユーザーのデータ登録

### ISSUE THREAD

**Issue by takeshikubota** [rexitorg/menta#24]
## 概要
チャット機能を実装しています。
「ChatRooms」「ChatRoomUsers」「Chat_messages」
のテーブルを作成しました。[ChatRoomUsers」テーブルに
ユーザーデータを保存してチャットページを開きたいと考えてます。

## 実現したいこと
ChatRoomUserにユーザーデータを保存したい。

## 困っていること

```
  def create
  # 自分の持っているチャットルームIDを取得
  current_user_chat_rooms = ChatRoomUser.where(user_id: @current_user.id).map(&:chat_room)

  # 自分の持っているチャットルームからチャット相手のいるルームIDを取得
  chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, post_id: params[:post_id]).map(&:chat_room).first
  # なければ作成する
  if chat_room.blank?
    # chat_roomsテーブルにレコードを作成
    chat_room = ChatRoom.create

    ChatRoomUser.create(chat_room: chat_room, user_id: @current_user.id)
    ChatRoomUser.create(chat_room: chat_room, post_id: params[:post_id])

  end
  # チャットルームへ遷移させる
  redirect_to action: :show, id: chat_room.id
end
```

## 解決するために行ったこと
```
    ChatRoomUser.create(chat_room: chat_room, user_id: @current_user.id)
    ChatRoomUser.create(chat_room: chat_room, post_id: params[:post_id])
```
で作成を試行錯誤しました。
「post=企業ユーザー　user=学生ユーザー」
@current_user.id と　params[:post_id]（２種類のユーザー）にはid
が入っていることをbinding.pryで確認しました。

## 問題となっている箇所の予想
```
    ChatRoomUser.create(chat_room: chat_room, user_id: @current_user.id)
    ChatRoomUser.create(chat_room: chat_room, post_id: params[:post_id])
```

## 問題となっているアプリケーションのGitHub URL
https://github.com/takeshikubota/hotel/blob/master/app/controllers/chat_controller.rb

**Comment by rexitorg** [comment]
> ChatRoomUserにユーザーデータを保存したい。

こちら実現したいことはこれでわかったのですが、現状はどういう挙動になっているんでしょうか？保存することができないのか。何が問題になっているのか困っているところがコードだけなので

`あるべき挙動（仕様）` と `現状の挙動` を記載して頂きたいです:bow:

**Comment by rexitorg** [comment]
`post_id: params[:post_id]` のところなどGitHubのソースコードが古そうなので最新状態に更新して頂きたいです:bow:

**Comment by takeshikubota** [comment]
`あるべき挙動（仕様）` 
ChatRoomUseテーブルにユーザーデーターを保存したい。

 `現状の挙動`
エラー表示はなく、
現状はテーブルにチャットユーザーの情報が保存されない状態です。参加者のIDは取得できておりcreateアクションでテーブルにデータ保存のコードを記述をしているのですが、テーブルを見ても何も保存されていない状態です。

失礼しました。ソースコードになります。
https://github.com/takeshikubota/hotel

**Comment by rexitorg** [comment]
確認します:bow:

**Comment by rexitorg** [comment]
[質問]
`post_id`ってなんでしょう？
https://github.com/takeshikubota/hotel/blob/master/app/controllers/chat_controller.rb#L7

あとここの分岐処理には入っていますか？binding.pryで処理実行すれば分岐に入るかどうかわかると思います:bow:
https://github.com/takeshikubota/hotel/blob/master/app/controllers/chat_controller.rb#L9-L15

**Comment by rexitorg** [comment]
あと

`user.rb`
```rb
class User < ApplicationRecord
  mount_uploader :img_name, ImgNameUploader

  has_many :posts, dependent: :destroy
  has_many :chat_messages
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users

  #validates:name,{presence:true}
  #validates:email,{presence:true,uniqueness:true}
  #validates:password,{presence:true}

  #def posts
  #  return Post.where(user_id:self.id)
  #end
end
```

とかしてやると

```rb
current_user.chat_rooms
```
でユーザーが所属するチャットルームが取得できるので良いかなと思いました。

**Comment by takeshikubota** [comment]
間違ってDoneにしてしまいました。
post_idですが。

post_id=会社
user_id=学生
と言う２つのユーザーいます。

この２つのユーザーでチャットが出来るようにしたいと考えています。

**Comment by takeshikubota** [comment]
頂いている質問は上記で記載している
こちらの内容でよろしいでしょうか。
分岐処理も確認しており、意図通りidが入っております。


「post=企業ユーザー　user=学生ユーザー」
@current_user.id と　params[:post_id]（２種類のユーザー）にはid
が入っていることをbinding.pryで確認しました。

**Comment by takeshikubota** [comment]
間違ってcloseボタンを押してしまい、Doneになっております。

**Comment by rexitorg** [comment]
おっと失礼しました:bow:

post_idで会社ユーザーというのは命名として正しくないのでやめた方が良いと思います。
また会社、学生というのはUserというリソースが持っている属性なので中間テーブルのカラムで表現する必要はないのかなーと思いました。
`User#role`みたいなカラムを用意してあげてそこに`student`とか`employee`とか持たせて上げる方が一般的ですね

で、本題ですが、コンソールのSQL実行結果をみてもらえればinsertするときにrollbackが発生していることがまずわかるのかなと思いました。
それで原因ですが

https://github.com/takeshikubota/hotel/blob/master/app/controllers/chat_controller.rb#L13-L14

の部分でuser_id or post_idに値を設定して保存しようとしているが

https://github.com/takeshikubota/hotel/blob/master/db/schema.rb#L26-L27

のスキーマ制約でuser_id, post_id共に`null: false`なので両方のカラムを埋めていないとinsertできないためエラーになって保存できないのだと思います。

**Comment by takeshikubota** [comment]
ありがとうございます。

`User#role`みたいなカラムを用意してあげてそこに`student`とか`employee`とか持たせて上げる方が一般的ですね
を詳しく教えていただきたいです。paramsやcurrentでidを持ってくる際に、１つのカラム（role）で別々の（student,employee）で振り分けは可能なのでしょうか。

**Comment by takeshikubota** [comment]
ありがとうございます。。
無事に解決できました。
ChatRoomUser.create(chat_room: chat_room, user_id: @current_user.id,post_id: params[:post_id])

保存出来ました。ありがとうございました。。

**Comment by rexitorg** [comment]
> `User#roleみたいなカラムを用意してあげてそこにstudentとかemployeeとか持たせて上げる方が一般的ですね`
を詳しく教えていただきたいです。やり方としてはUNIONを使用するということでしょうか。

違います。ユーザーの役割が分かれているので属性（プロパティ）として持たせるのが良いという話ですね。

例えばusersテーブルで下記のように持たせるのが良いのかなと。

```
user_id,role
1,employee
2,student
```
下記は正規化している記事ですが直接valueとして設定しても良いとは思います。

https://waterlow2013.hatenablog.com/entry/2017/01/27/233405

中間テーブルchat_room_usersはチャットルームに所属しているユーザーを管理できれば良い話なので役割は関係ないですよね。

chat_room_usersテーブルで

```
id,chat_room_id,user_id
1,1,1
2,1,2
```

みたいにすれば所属しているユーザーは管理できるのかなと思いました。

**Comment by rexitorg** [comment]
> ありがとうございます。。
無事に解決できました。
ChatRoomUser.create(chat_room: chat_room, user_id: @current_user.id,post_id: params[:post_id])
保存出来ました。ありがとうございました。。

良かったです:smile:処理するときにコンソールにSQLの実行結果が出力されているはずなのでそれを確認すると何が起きているかわかると思います！
また`bundle exec rails c` とかでrailsコンソールを立ち上げて実際に保存する処理だけを実行するのもデバッグ手法の一つです。今回の場合だと保存するところで問題になっているので
```rb
chat_room = ChatRoom.create
ChatRoomUser.create(chat_room: chat_room, user_id: 1)
```

とか適当に実行してみればどういった挙動になっているか確認できると思います:bow:

**Comment by takeshikubota** [comment]
ありがとうございます。
前回含め、エラー時の対処を身につけていきます。
ありがとうございます。

今回のメールの内容は今行っております。
よろしくお願いします。


2019年2月16日(土) 10:46 konchan <notifications@github.com>:
