### ISSUE TITLE
モーダルウィンドウのテスト実装方法について質問です。

### ISSUE THREAD

**Issue by shyuhei-kaneko** [rexitorg/menta#25]
## 概要
モーダルウィンドウ実装に向けて下記記事を参考にさせて頂いています。
https://qiita.com/Kolosek/items/4ee80eb0c6dd0af4b1b7

## 実現したいこと
webページに準じたテストウィンドウを作成する。

## 困っていること
・webページに記載されている
　　new.js.erb
　　$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
　　$("#modal-window").modal();
について何処のディレクトリにおけば良いのか分かりません。

・実施要項に抜けが無いか・各ファイルの置き場所が合っているか確認して頂きたい
　PR参照願います。
## 解決するために行ったこと
原因がわからないので実施出来ず

## 問題となっている箇所の予想
不明

## 問題となっているアプリケーションのGitHub URL
https://github.com/shyuhei-kaneko/attendance-system/pull/3/commits/309d3a5f5323ab92dc93bfdd325d01d68fc86ddd

**Comment by rexitorg** [comment]
erbファイルなのでview配下で良いと思います:bow:こちらの記事も参考にしてみてください:bow:
https://qiita.com/niwaken/items/ffbce52fb024fd369f24

全項目を満たしているか私の方で確認して行くのは流石に実作業が結構大きいので、、、動作しないようでしたら再度質問お願いします:bow:
