### ISSUE TITLE
キャリア形成に関して

### ISSUE THREAD

**Issue by RYUTAONO0929** [rexitorg/menta#26]
## 概要
以前、回答(インターンに関して)頂いたことを考えゆくなかで自分のキャリア形成について不透明な点がでてきたのでご助言いただきたいです。
・なぜブロックチェーンなのか？
1.書籍(「これからを稼ごう」等)を読み漠然と将来ブロックチェーン技術の普及を肯定的に考えるようになった。
2.ゼミの担当教員からエストニアのような国に興味があることを伝えると、ブロックチェーンに関する理解が必要であることを指導頂いた。
・何を学びたいのか？
上記の内容より、 ブロックチェーンが普及するだろう→ゼミ内でもプログラミングを勉強するのでプログラミングの学習は必要→Rubyという言語がわかりやすく日本では普及しているらしい→とりあえずRails を使いこなせるようになってwebアプリケーションを作り大学生の間アルバイトの代わりに稼ぎたい→大学院卒業後はブロックチェーン関連の就職もしくは起業したいのかもしれない→rubyを勉強しよう
という思考です。
・何を目指しているのか、キャリアプランは？
ITの業界に関して深く知っておらず、自分がどのようなキャリアを形成していったら良いのかわからない。
漠然といつかは起業と思っている。

## 実現したいこと
これからの自分キャリア形成についてのアドバイスやキャリアのモデルを教えていただきたいです。
具体的には、今後2〜4年の間と大学院卒業後のキャリアについてです。

## 困っていること
方向性が定まらずプログラミングの勉強のモチベーションが保てない。

**Comment by rexitorg** [comment]
現状が漠然としたものしかなく具体的なイメージがないことが課題なのかなと思いました。まずはイメージできるような知識や経験を積んでいくのが良いかなと思います。一番手っ取り早いのは働いてみる。ですね。アルバイトで良いので未経験でもできるところを探してやってみるのが一番早いと思います。その中で自分にIT業界やエンジニアという職業が向いているかどうかわかるのかなと思います。

> これからの自分キャリア形成についてのアドバイスやキャリアのモデルを教えていただきたいです。

これは人それぞれなのでなんとも言えない部分もあると思いますが、自分だったらこうするを記載しておきます。いきなりなんのスキルもないまま起業して成功する人もいると思います。

(1)未経験でも可能なところを見つけてアルバイト、インターンをする
(2)IT業界が向いているかどうか判断する
(3)Webエンジニアに向いているようであればプログラミングを勉強する。例えばRuby,Railsをやる。
(4)自社サービス開発の企業に就職する。
(5)Webエンジニアとして3年くらい経験を積む。
(6)起業する。

ブロックチェーンの知識、技術については自社サービス開発の企業がそれをやっていれば手っ取り早く学べるかなと思います。それ以外でもプログラミングの基礎技術が身について入れば自分で調べることもできるし、副業とかでスキルは習得できるのかなと思います。

**Comment by rexitorg** [comment]
@RYUTAONO0929 
こちら一旦closeしますね:bow:
