### ISSUE TITLE
現場で使えるrails速習１

### ISSUE THREAD

**Issue by RYUTAONO0929** [rexitorg/menta#29]
## 概要
WSLにrbenvをインストール時にエラーが発生します。

## 実現したいこと
現場で使えるRuby on Rails5速習ガイド
2-2-2
p57

## 困っていること
E: Unable to locate package zliblg-dev
E: Unable to locate package libgdbm3　と出力される

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
ryutaono@DESKTOP-G6D20US:~$ sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev  libreadline6-dev zliblg-dev libncurses5-dev libffi-de
v libgdbm3 libgdbm-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
E: Unable to locate package zliblg-dev
E: Unable to locate package libgdbm3

## 解決するために行ったこと
参考書を見直しましたが間違いをみつけることはできませんでした

**Comment by RYUTAONO0929** [comment]
エラーの二つのうち一つ目はtypoだとわかりましたが、二つ目がなぜインストールできないのかわかりません。
宜しくお願い致します。

**Comment by RYUTAONO0929** [comment]
また、このエラーのためかruby -v としてもバージョンが表示されずにエラーになります

**Comment by rexitorg** [comment]
現場Railsもやってるんですね〜
OSがWindowsなんですね。ちょっと手元にmacしかないので的確にアドバイスできるかわからないですが、

```
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
```

と記述があるので

```
$ sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline-dev zliblg-dev libncurses5-dev libffi-de
```

としたらどうなりますか？

**Comment by rexitorg** [comment]
あれでもこちらの記事だと無視して良いとありますね

https://qiita.com/ninoko1995/items/2ce494507169f461399f

上記の記事の
https://qiita.com/ninoko1995/items/2ce494507169f461399f#rbenv%E3%81%AB%E3%82%88%E3%82%8Brails%E7%92%B0%E5%A2%83%E4%BD%9C%E6%88%90

から試してもらって良いでしょうか？

**Comment by RYUTAONO0929** [comment]
御指定いただいたホームページの通りに進めたところruby -v でrubyのバージョン確認　rails -vでrailsのバージョン確認ができるようになりました。

**Comment by rexitorg** [comment]
おお、一旦解決したようで良かったです:bow: こちらはcloseしておきます:smile:
