### ISSUE TITLE
困っている事　その２（slackから転載）

### ISSUE THREAD

**Issue by shyuhei-kaneko** [rexitorg/menta#3]
# 概要
現在railsで作成中のシステムが御座います。
概要といたしましては勤怠情報をを管理するシステムとなっています。
・サインアップ、ログイン機構がございます。
・ユーザー情報とそれに紐づく勤怠情報が存在しています。それぞれモデルに記録していきます。
・ログイン後に勤怠情報を記録・表示するページが表示されます。
・ユーザーは自身のみの勤怠情報や基本情報に関して編集を行う事が可能です。
・他のユーザーとは別の管理者アカウントという物が存在しています。
　　管理者は他のユーザー一覧を閲覧、編集が可能となっています。
　　管理者はユーザー一覧から任意のユーザーを選択後、勤怠情報を自由に編集する事が可能です。
簡単では御座いますが以上がシステムの概要となります。

Git Hub URL
https://github.com/shyuhei-kaneko/Intern-Attendance-B/tree/master
masterブランチを参照願います。

管理者情報
メールアドレス
admin@gmail.com
パスワード
foobar
名前はadmin

# 実現したいこと
一ヶ月分の勤怠情報の一括編集機能を実装したい。

# 困っていること
勤怠情報一括編集ボタンが効かない
(入力フォームへ値を入力後にボタンを押下しても反応しない)
以前はキチンと動いていました。
しかし当月の情報しか編集出来ないという不具合を対応しまして、showページ側から該当月の値(＠first_day)をcontroller(def attend_edit)側へ引き渡しています。
その対応後以降、押下しても反応しなくなってしまいました・・・。

概要についてはslack DM画面キャプチャを参照願います。

# 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
問題点の原因が掴めていない為対応方法が分かりません。

# 解決するために行ったこと
原因がわからない為対応方法が分かりません

# 問題となっている箇所の予想
変数等の値が上手くメソッドへ渡っていない？

**Comment by rexitorg** [comment]
原因の予想

ルーティングにパラメータを含める形にしたのでその影響だと思います。routes.rbも修正しないとルーティングパスが一致しないのでエラーになっているのかなと思いました。

https://github.com/shyuhei-kaneko/Intern-Attendance-B/blob/basic/config/routes.rb#L13-L14

アクションを呼び出すためにルーティングを合わせる必要があると思います。
https://railsguides.jp/routing.html

**Comment by shyuhei-kaneko** [comment]
お世話になります。

＞ただfirst_dayの仕様がわかってないので本当に渡す必要があるのか自分もまだ把握できてないです。
first_dayはshowページで表示している「月」の情報です。(showページでは任意の月情報を表示させる機能がございます。)
勤怠一括編集する月の情報表示をする為にfirst_day(表示月の情報)を渡している。という意図がありました。 ・・伝わりますでしょうか？

＞これ勤怠についてもusersで処理してしまってるんですね。Fat controllerになるのであまり良くない実装かもしれないです。
＞attendance（勤怠）というresourceを編集するなら

＞resource :attendancesとかをroutes.rbに定義してあげるのが本来は良いです。
bluk_editという名前でブランチを切ってご指摘の部分修正致しました。git hubへpushもしています。

＞ロジックとしてはここですかね？
そちらでなく下記になっております。
https://github.com/shyuhei-kaneko/Intern-Attendance-B/blob/bulk_edit/app/controllers/attendances_controller.rb
94行目の部分になります。

あと、困っている事についてもう一度共通認識として確認したいのですが、
attend_edit.html内にある%= f.submit "編集を保存する", class: "btn btn-primary"
%>ボタン押下時に反応しなくて困っている。
skack内のDMに画像もありますのでそちらも見て頂くとイメージつきやすいと思います。
認識と相違ないでしょうか

以上です。よろしくおねがいします。


2019年1月10日(木) 4:46 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
> 勤怠一括編集する月の情報表示をする為にfirst_day(表示月の情報)を渡している。という意図がありました。 ・・伝わりますでしょうか？

なるほど、これは日付である必要はあるんでしょうか？年月情報でも良い？と思ったりしました

> bluk_editという名前でブランチを切ってご指摘の部分修正致しました。git hubへpushもしています

branchをpushするだけだと修正箇所がわからないので通常その場合はPR(Pull Request)を作成していただくことになると思います！
https://github.com/shyuhei-kaneko/Intern-Attendance-B/pulls
このページから`New Pull Request`を選択して切り出し元branch向けにPRを作成して頂ければと思います:bow:

> 94行目の部分になります。

L94の部分はパラメータが渡ってきてeditのアクションが実行された時のロジックですよね？`users#show`を表示してeditを押下する際にリクエストパラメータとして渡すのは`def show`内で定義しているパラメータになるのかなと思いました。と思ってましたが事象を勘違いしていたかもしれないです。

> あと、困っている事についてもう一度共通認識として確認したいのですが、
attend_edit.html内にある%= f.submit "編集を保存する", class: "btn btn-primary"
%>ボタン押下時に反応しなくて困っている。
skack内のDMに画像もありますのでそちらも見て頂くとイメージつきやすいと思います。
認識と相違ないでしょうか

こちら勘違いしていました `勤怠を編集` を押下した際にeditページに遷移しないといった事象かと思っておりました。申し訳ございません:bow: 

<img width="1440" alt="2019-01-07 21 06 29" src="https://user-images.githubusercontent.com/13507595/50983738-74517b80-1543-11e9-9402-541c4981fd4a.png">

<img width="1440" alt="2019-01-07 21 06 48" src="https://user-images.githubusercontent.com/13507595/50983747-7ca9b680-1543-11e9-9640-3db097714299.png">

添付しましたmm

こちら反応しないというのは`def attend_update`の処理を通っているかどうかは確認済みでしょうか？

あと気になったところとしてコードのインデントが揃ってないのでエディタのautoformatterとかを使って揃えた方が良いと思います:bow:

**Comment by shyuhei-kaneko** [comment]
＞branchをpushするだけだと修正箇所がわからないので通常その場合はPR(Pull Request)を作成していただくことになると思います！
https://github.com/shyuhei-kaneko/Intern-Attendance-B/pulls
このページからNew Pull Requestを選択して切り出し元branch向けにPRを作成して頂ければと思います

申し訳ありません。PR作成致しました。(初めてだったのですが多分大丈夫だと思います。)
https://github.com/shyuhei-kaneko/Intern-Attendance-B/pull/3

＞def attend_updateの処理を通っているかどうかは確認済みでしょうか？
こちら確認しました所通っていない様でした。
方法はdef attend_updateでデバックをかけて「編集を保存する」を押下してみた所デバックの反応が無かった事を確認しました。
これはルーティングの
  patch  'attend_update' => 'attendances#attend_update'
が怪しいと考えられるのでしょうか


＞コードのインデントが揃ってないのでエディタのautoformatterとかを使って揃えた方が良いと思います
知らない内容でしたので自分なりに調べて見ましたが分かりませんでした。
解説記事等ありましたら添付していただけると嬉しいです。

2019年1月11日(金) 2:01 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
> PR作成致しました。(初めてだったのですが多分大丈夫だと思います。)

こちらdescriptionにどういった変更を入れたのかなど説明の記載をお願いします:bow:PRはコードの変更に関して説明を記載してレビューしてもらうものなので見てもらう人に自分がやったことをできるだけわかりやすく伝える必要があります

**Comment by shyuhei-kaneko** [comment]
承知しました。先ほどdescriptionへ説明記述致しました。

2019年1月11日(金) 10:05 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
> 承知しました。先ほどdescriptionへ説明記述致しました。

こちらmergeされてしまっているようです:cry:

**Comment by shyuhei-kaneko** [comment]
申し訳ありません。
注意致します😥

2019年1月11日(金) 11:16 konchan <notifications@github.com>:

**Comment by rexitorg** [comment]
大丈夫です！ただ未レビューのものがmergeされるのはよくないのでrevertという処理で戻してもらうことは可能でしょうか？
こちらが参考になるかなと思います！
https://blog.github.com/2014-06-24-introducing-the-revert-button/

またこちらの後半部分もご確認よろしくお願いします:bow:
https://github.com/rexitorg/menta/issues/3#issuecomment-453327379

**Comment by shyuhei-kaneko** [comment]
revertの件、承知いたしました。
只、今回の困っている事その２におきましては解決致しました！
今回、PR、merge、revertに関しても勉強になりました。
ありがとうございました。

**Comment by shyuhei-kaneko** [comment]
承知致しました。
原因
htmlの記述に問題があった。
↓
tableタグの中にformタグを書いてしまっていた。

対応内容
formタグをtableタグの上部へ移動させた。
以上です。

**Comment by rexitorg** [comment]
ありがとうございます。
こちらの内容が近そうですね:smile:
http://tkoyama1988.hatenablog.com/entry/2014/01/01/165437

今回の場合だと

table開始
form開始
table終了
form終了

というDOM構造になっていたのも宜しくなかったのかなと思いました:bow:

**Comment by rexitorg** [comment]
@shyuhei-kaneko こちら解決したようなのでcloseしておきます:bow:
