### ISSUE TITLE
一覧画面での変更方法

### ISSUE THREAD

**Issue by yoshimitsu41** [rexitorg/menta#35]
## 概要
rails初心者です。

レンタル事業を行っており、自社で顧客管理を行うためのappをrailsで作っております。
クローズドなappでid,passを入れて閲覧するようになっています。
※中身はめちゃくちゃだと思いますが自分で作りました。

appの活用の流れとして…

お客さんからレンタルの予約が入る
→顧客管理appに入力する(名前、連絡先、レンタル日時など)
→登録するとGoogleカレンダーに反映して、スタッフがその予定を確認する
→入金の管理などもapp内でおこっており、入金確認等のステータスを作っている。

といった感じのappです。

## 実現したいこと
・レンタル予約一覧画面
・レンタル予約詳細画面
があるのですが、入金ステータス、発注ステータスがenumで対応していす。
例えば、入金ステータス(integer型でenum)【未入金・請求済み・入金済み】といったものがあり、一日に10件とか確認して変更する場合、わざわざ一つ一つの編集画面を開いて、ステータスを変更すると行った手間がかかります。

そこで予約一覧画面でクリックするとプルダウンで選べて、入金ステータスを変更できるように仕様を変更したいと思っています。

## 困っていること
一覧画面でどのようにして変更すれば良いのかわからないです。

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
バグではありません。

## 解決するために行ったこと
ネット上で情報を探しましたがうまく見つけることができませんでした。

## 問題となっている箇所の予想
一覧画面でAjaxを使って対応するのだと予想しているのですが、正しいかどうかもわかっていません。

## 問題となっているアプリケーションのGitHub URL
1年半ほど前に作ったアプリで、bitbucketを使ってバージョン管理していました。
googleカレンダーのAPIキーや、その他公開しては行けない情報が入っているので、プライベートで対応しています。
そのため、bitbucketのユーザーに招待したいと思いますので、ユーザー名か、メールアドレスを教えて下さい。

**Comment by rexitorg** [comment]
> googleカレンダーのAPIキーや、その他公開しては行けない情報が入っているので、プライベートで対応しています。

こちら自分は閲覧可能な状態になりますが、大丈夫でしょうか？...
当然悪用などするわけではないですが、万が一自分がウイルス感染などしたケースなども想定されますし。
こういった情報はソースコード管理ではなく環境変数で管理するのが良いかなと思います。
可能であれば

- ソースをコピー
- 環境変数にする
- `.git`ファイルを削除して作り直す。（履歴が消える）
- GitHubのprivateにあげる

とかすると良いと思いました。一旦ご確認宜しくお願いします:bow:

**Comment by yoshimitsu41** [comment]
ありがとうございます。
先程rexitorgをプライベートリポジトリに招待しました。
githubの知識が低のですが、ソース見れますでしょうか？

**Comment by yoshimitsu41** [comment]
![2019-02-22 11 42 21 1](https://user-images.githubusercontent.com/17039500/53216190-2b8af780-3697-11e9-8b4a-ae7eac9d4a45.jpg)

赤丸の部分を変更したいときに、わざわざ[edit]ボタンを押してから変更しているのですが、一覧画面でプルダウンで変更できるようにしたいといった内容になります。

**Comment by rexitorg** [comment]
みれました！

**Comment by rexitorg** [comment]
これって確認画面とか必要ないんでしたっけ？
一つ一つ変更するのがめんどうなのであればAjaxで処理しなくても一括編集画面みたいなの用意してそこでプルダウンで選択した後に変更確認画面みたいなところにとんで一括変更反映みたいなことをした方が実用的？と思ったりました。

**Comment by yoshimitsu41** [comment]
確認画面は必要ないです。
一括編集は考えたことなかったです。
一括編集用のアクションとビューを作って、必要な情報だけ変更できるようにしたら良いかもしれないですね。一度試してみます！
試してみて実装方法で問題が起これば再度ご相談します！
ありがとうございます。

**Comment by rexitorg** [comment]
おお、承知しました:bow:
こちらのissueはcloseしておきます:bow:
