### ISSUE TITLE
Deviseでの[Couldn't find User]エラーについて

### ISSUE THREAD

**Issue by sumura80** [rexitorg/menta#4]
# 概要
「Couldn't find User with 'id'」について教えていただけませんでしょうか。
Deviseを使っているのですが、URLにテストとしてありえないuser idを入力するとエラーになります。
ありえないUser idだけでなく、アカウントを消したUserのidをいれても同じエラーになる。

# 実現したいこと
1.実務ではこのエラーをどのように解決するかを知りたい。
2.このエラーは404/500エラーとは違うと思うので、「このようなユーザーは存在しません」というようなエラーのテンプレートを表示し、rootか他のページに誘導したい。

# 困っていること
対処の仕方がわかりません。（解決するためのコードの書き方）

# 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
エラーを下記に記載しました。

ActiveRecord::RecordNotFound in UsersController#show
Couldn't find User with 'id'=940 [WHERE "users"."deleted_at" IS NULL]
```
def show
　@user = User.find(params[:id])
　@comments = Comment.order("created_at DESC").where(user_id: @user.id)
end
```

# 解決するために行ったこと
whereを使い、userで存在するユーザーを選択するのかと思い、下記のように記述しましたがエラーになってしまいした。
@user = User.find(params[:id]).WHERE("users"||"deleted_at" IS NULL)

# 問題となっている箇所の予想
app/controllers/users_controller.rb

**Comment by rexitorg** [comment]
@sumura80 
回答しました！:bow:

**Comment by sumura80** [comment]
@rexitorg 
ご教示いただきありがとうございました。
例外処理を復習してから実際にコードを書いてみますので、その時にもう一度ご確認いただけますでしょうか？少々お待ちくださいませ。

**Comment by rexitorg** [comment]
はいー:bow:
確認というかPRを作成してレビュー依頼をして頂ければと思いますmm

**Comment by rexitorg** [comment]
@sumura80 こちら状況どうでしょうか？

**Comment by sumura80** [comment]
エラーの対処法なのですが、とりあえずRailsで作成される下記のエラーのhtmlを、下記のサイトにある様に編集するだけにしてみようかなと考え中なのですが、それもありでしょうか？:sweat_smile:
・public/400.html
・public/422.html
・public/500.html


https://qiita.com/dach1_ken/items/6bbdfdd56ef84e3b2233

**Comment by rexitorg** [comment]
はい、まあ良いと思います。ユーザーがnot foundの時のエラー画面を出す必要がないようであればそれで問題ないと思います:bow:
controllerで例外キャッチして静的エラーページにハンドリングすれば良いかなと思います:bow:

**Comment by sumura80** [comment]
ありがとうございました。
その様に作成したいと思います。
