### ISSUE TITLE
運用中のherokuappのDBの操作

### ISSUE THREAD

**Issue by yoshimitsu41** [rexitorg/menta#41]
## 概要
herokuでアップされているrailsアプリがあります。
ローカル開発でhas_oneのアソシエーションを追加（Bモデルとする）。
Bモデルは、Aモデルで情報を追加すると自動的にBモデルの情報が追加されるようにしました。

仕組み的にAモデルを作成(create)かアップデート(update)をしないとBモデルの内容がつくられないようなものです。
herokuにあるDB(mysql)にもBモデルの内容を反映させたいのですが、どのようにすればいいのでしょうか？
ちなみに運用しているDBにはAモデルのデータは約1000件あります。

## 実現したいこと
運用しているアプリに一括でDBに情報を入れたい。

## 困っていること
どのようにして一括でデータを入れるのかがわからない。

## 解決するために行ったこと
解決方法がわかりません。

## 問題となっている箇所の予想
seeds.rbを使う方法？
heroku上を情報を変更しないまま一括でupdateさせる？

## 問題となっているアプリケーションのGitHub URL
以前にお送りしたmenta_bbqです。

**Comment by rexitorg** [comment]
seeds.rb を使ってテストデータを流し込めば良いかなと思います:bow:

**Comment by rexitorg** [comment]
ymlとかcsv,tsvあたりでテストデータのファイルを作成してそれを読み込んで`bundle exec rails db:seed` でcreateするとかすれば一気に反映することができます:bow:

**Comment by yoshimitsu41** [comment]
csvでテストデータを作成してインポートしようとしたのですがエラーがでてインポートができません。
入れるカラムとして…。
price,
bbq_status
bbq_id
bba_day
です。
エラーは下記です。
```
$ bundle exec rails db:seed
rails aborted!
ArgumentError: '1' is not a valid bbq_status
/Users/yoshimitsu/rails_app/bbqnow/db/seeds.rb:12:in `block in <top (required)>'
/Users/yoshimitsu/rails_app/bbqnow/db/seeds.rb:11:in `<top (required)>'
/Users/yoshimitsu/rails_app/bbqnow/bin/rails:9:in `require'
/Users/yoshimitsu/rails_app/bbqnow/bin/rails:9:in `<top (required)>'
/Users/yoshimitsu/rails_app/bbqnow/bin/spring:15:in `require'
/Users/yoshimitsu/rails_app/bbqnow/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

seeds.rbは下記です。
```
require "csv"

CSV.foreach('db/sample.csv') do |row|
  MoneyHistory.create(:bbq_id => row[0], :bbq_day => row[1], :bbq_status => row[2], :price => row[3])
end
```
bbq_statusが問題だと思うのですが解決方法がわかりません。

試しにbbq_statusを省いてインポートしてみたのですが、うまく入りました。
問題箇所はございますでしょうか？

**Comment by yoshimitsu41** [comment]
![2019-02-26 21 02 19](https://user-images.githubusercontent.com/17039500/53411499-f6b9d000-3a09-11e9-87f3-c70b96672286.jpg)

**Comment by yoshimitsu41** [comment]
すみません。
自己解決しました。
モデルで
`enum bbq_status:{申し込み:0 ,仮予約: 1,キャンセル: 2}`
を指定していたためインポートができなかったです。
失礼致しました。

**Comment by rexitorg** [comment]
お、承知しました:bow:
解決されたようなのでcloseしておきます:bow:
