### ISSUE TITLE
Railsテキストエディタについて

### ISSUE THREAD

**Issue by yuumasakura777** [rexitorg/menta#57]
## 概要
お疲れ様です。
現在Ruby on rails速習実践ガイドをしていまして、ローカル環境に環境構築できたのですがcloud9と仕様が違っており戸惑っています。
そこで質問があるのですが、ターミナルからコマンド操作しないとフォルダ内のファイルを開けないのですか？（cloud9時は左側にフォルダが出現しそこから使いたいフォルダのファイルをクリックしていました。）

## 実現したいこと
どのテキストエディタを使えばいいか。
テキストエディタとターミナルをどう連携させればいいか教えていただけると助かります。

**Comment by soipon05** [comment]
速習ガイドって確かVScode勧めていませんでしたっけ？
自分はVScodeでやり抜きましたけど画面下部にターミナルも開けますしc9と同じように左側にファイルツリーの状態で表示されます！
JSの時の画像ですが、
対象のフォルダ開けばこんな感じでできますよ
![vscode](https://user-images.githubusercontent.com/33271639/54889466-22848480-4ee8-11e9-87bd-89f8cd4025ae.png)

**Comment by konchanxxx** [comment]
自分はVScode使ったことないですが、使っている人もいるのでありだと思います:bow:
あと無料のやつならAtomとかが使っている人多いですかね
https://atom.io/

有料ならRubyMine。これはRubyに特化したエディタです。
https://www.jetbrains.com/ruby/

あとはVimとかでやっている人が多い印象ですね。

**Comment by yuumasakura777** [comment]
Atomを使うことにしました！
ありがとうございました!
