### ISSUE TITLE
rails s について

### ISSUE THREAD

**Issue by username-ss** [rexitorg/menta#6]
# 概要
rails s を　control + Cで停止できなくなった

# 実現したいこと
rails s の停止

# 困っていること
概要に同じ

# 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
rails s
=> Booting Puma
=> Rails 5.2.2 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.0 (ruby 2.3.7-p456), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2019-01-13 14:57:03 +0900
Started GET "/" for 127.0.0.1 at 2019-01-13 14:57:03 +0900
   (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ /Library/Ruby/Gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/log_subscriber.rb:98
  ↳ /Library/Ruby/Gems/2.3.0/gems/activerecord-5.2.2/lib/active_record/log_subscriber.rb:98
^C
^C

# 解決するために行ったこと
control + C を通常通り行ったものの起動しない

# 問題となっている箇所の予想
migrationファイル

**Comment by username-ss** [comment]
VS code で書いていますが、ctrl + q を実行してもサイドバーが動くのみで…。

**Comment by rexitorg** [comment]
VScodeの組み込まれているターミナルってことですよね？
VScode使ってことないですが、ちょいちょい発生している不具合みたいですね
https://qiita.com/k_takashi0309/items/5aba084b850936eee7aa
https://github.com/Microsoft/vscode/issues/28635

個人的にはターミナル操作はiTerm2とかを使う方が良いと思います。
プロセスkillするなら

```
$ ps aux | grep rails
```

とかしてプロセス番号を指定してkillするのが良いと思います。

https://qiita.com/shuntaro_tamura/items/4016868bda604baeac3c

**Comment by rexitorg** [comment]
再起動で一旦解決したのでcloseします:bow:
