### ISSUE TITLE
viewの表記について

### ISSUE THREAD

**Issue by soipon05** [rexitorg/menta#62]
## 概要
現在いろんな方のviewの表記を見ているのですがその中にわからない項目があったので質問です。

## 実現したいこと
- col ||= 'col-sm-6 col-lg-4'
%div.mb-4{class: col}
haml表記で上記が何をしてるのかがわからない。
単純に.mb-4.col-sm-6.col-lg-4ではいけないのかの確認

## 困っていること
なぜこのような表記なのかわからないのと正解が自分ではわからない
## 解決するために行ったこと
試しに書いてみることはしました。

**Comment by konchanxxx** [comment]
自分もhaml詳しくないですけど

```
col ||= 'col-sm-6 col-lg-4'
```

の部分はRubyの変数代入のイディオムですね
https://www.xmisao.com/2014/02/10/ruby-idiom-or-equal-operator.html
ぶっちゃけここで使う必要ないのでこれは記述している人が間違っていると思います。

%div.mb-4{class: col}のところは変数展開している感じですね
hamlはRubyの変数を展開できるようです:bow:
https://morizyun.github.io/blog/beginner-rails-tutorial-haml/index.html

**Comment by konchanxxx** [comment]
> 単純に.mb-4.col-sm-6.col-lg-4ではいけないのかの確認

一箇所書くだけとかなら上記で良いです。
何回も同じ記述を繰り返して書くようなら変数にいれたりするほうが楽だし、共通化できるので間違いがなくなるというメリットがあるかなと思います。

**Comment by soipon05** [comment]
回答ありがとうございます！
とりあえずは変数を使えるということと直書きでも特段問題ないという認識で行こうと思います。
現場によりけりだとは思いますが大きな現場になると教科書以上に複雑だと思うのでこれがスタンダードなのかな？って迷いが解決されました！
