### ISSUE TITLE
Heroku デプロイ後、一定時間すると画像表示されなくなってしまう

### ISSUE THREAD

**Issue by shumatsumoto** [rexitorg/menta#67]
## 概要
https://insta-shu0328.herokuapp.com/
techpitの教材に沿って、インスタグラム風アプリすすめてます。
Herokuデプロイまではうまくいったのですが、
画像投稿してみて、少し経つと画像が表示されなくなってしまう。。

## 実現したいこと
本番環境でも、問題なく画像が表示されるようにしたい。

## 困っていること
Herokuでの画像の扱いについて知りたいです。

※あと気になったことありまして。
いま自宅ではCloud9とHerokuでRailsの制作してるんですが、
実務では、どのような環境ですすめるのが一般的なのでしょうか？
Docker等も必要なのですかね？
（ちょっと見当外れな質問かもですが、分かる範囲でご教示いただけたら助かります！）

## 解決するために行ったこと
QiitaなどでもHerokuの画像投稿について色々出てきまして、
どれに該当するのかよく分からず。。

## 問題となっている箇所の予想
投稿して少しの間は画像表示されてます。。
画像は本番環境用に別途、対応が必要なのかな？

**Comment by konchanxxx** [comment]
> https://qiita.com/hmmrjn/items/b02f076ceaeeaaceb999

Herokuは画像が消えちゃうのでS3などにストレージを変更する必要がありますね:bow:

> 実務では、どのような環境ですすめるのが一般的なのでしょうか？

ローカル開発環境を構築してAtom,VSCodeやRubyMineなどのエディタを使い、dev開発環境,本番はAWSとかGCPですね。Dockerは現時点だとなくても大丈夫だと思います:bow:

**Comment by konchanxxx** [comment]
あとこの問題調べる時ってどうやって調べましたか教えていただきたいです:bow: 最終的には自分で調べて解決していける状態にならないといけないので調べ方について改善していけたらなと思いました:bow:

**Comment by shumatsumoto** [comment]
ご確認ありがとうございます！
失礼しました～
仰る通りで、自力で出来るようにならないといけませんもんね！
頂いたQiitaのも確認してましたが、
konchanさんに聞いたのが間違いない情報と思いまして、とっさに連絡した次第です。
実際に試しておらず、怠け心でした(*_*)
今後ともよろしくお願いします！

**Comment by konchanxxx** [comment]
なるほど！承知です:bow: ありがとうございます:smile:
