### ISSUE TITLE
rails db: migrate実行時にエラー

### ISSUE THREAD

**Issue by yuumasakura777** [rexitorg/menta#68]
## 概要
掲示板アプリを作っていたのですが、rails db:migrateを実行したときにエラーが出てしまいました。そのエラーのため次に進めなくなってしまいました。

## 困っていること
エラーを解決したいです。

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
バグ事象　

```
ActiveRecord::PendingMigrationError

Migrations are pending. To resolve this issue, run: bin/rails db:migrate RAILS_ENV=development

  # Raises <tt>ActiveRecord::PendingMigrationError</tt> error if any migrations are pending.
      def check_pending!(connection = Base.connection)
        raise ActiveRecord::PendingMigrationError if connection.migration_context.needs_migration?
      end

      def load_schema_if_pending!
```

## 解決するために行ったこと
rails db:rollbackを行いましたが変化はありませんでした。

 @#[##](url) 問題となっている箇所の予想

**Comment by soipon05** [comment]
bin/rails db:migrate RAILS_ENV=development
このコマンド実行してね~って書いてありますけど実行しました？
リセットしても問題ないようであれば
rails db:reset
rails db:migrate
の順でやってみたら上手く行くかもしれないです？

**Comment by yuumasakura777** [comment]
rails db:resetで上手く戻れました。
ありがとうございました！
