### ISSUE TITLE
dotenvの環境変数の読み込みをJSファイルで行いたい

### ISSUE THREAD

**Issue by soipon05** [rexitorg/menta#70]
## 概要
JSファイルに記述してある環境変数が読み込まれない
ENV['STRIPE_PUBLISHABLE_KEY']

## 実現したいこと
JSファイルに記述している環境変数を正しく読み込みさせたい

## 困っていること&解決するために行ったこと
JSファイルにkeyを直書きしているので環境変数を記述して読み込ませれるようにしたい

## 問題となっている箇所の予想
Dotenvはrbファイルのみでしか適応されないから読み込まれていないのかなと予想しています。

**Comment by konchanxxx** [comment]
@soipon05 
gonというgemを使うとRailsの変数をJSに渡せるようになりますね:smile:
https://qiita.com/s_nakamura/items/5d153f7d9db1b1190296

**Comment by soipon05** [comment]
できました！
ありがとうございます！
