### ISSUE TITLE
Deviseでの"Forgot your password?"のエラー

### ISSUE THREAD

**Issue by sumura80** [rexitorg/menta#73]
## 概要
Deviseを使用しており、”Forgot your password"の機能を利用すると、メールがきた時にURLをクリックするとエラーになります。

## 実現したいこと
Deviseの”Forgot your password"の機能を使えるようにしたい。

## 困っていること
"Change your password"を押すと"Not Found"エラーがです。

下記が自分の行ったプロセスです。
1. このようにDeviseを使って `Forgot your password?` をクリックしたとします。

![1](https://user-images.githubusercontent.com/17425060/56291641-99681280-6160-11e9-9222-97339c47cfd8.png)

2.するとこのようにメールアドレスを入力する欄にいき、送信します。
![2](https://user-images.githubusercontent.com/17425060/56291661-a38a1100-6160-11e9-8bc3-306f47179047.png)

3.そうすると自分に送信されたことが  `flash` で表示されます。

![3](https://user-images.githubusercontent.com/17425060/56291691-b13f9680-6160-11e9-9030-e71ca80fd1e5.png)

4.そうすると先ほど送信した宛先にパスワードを変更できる `Change my password` URLが送られきます。
![4](https://user-images.githubusercontent.com/17425060/56291703-b866a480-6160-11e9-8866-2cd7a0a36a50.png)

5. しかし、このURLを押すと `Not Found` が表示されてしまいます。
![5](https://user-images.githubusercontent.com/17425060/56291714-bf8db280-6160-11e9-88aa-118b50aadb5c.png)

/app/views/devise/passwords/edit
のファイルは存在しているのですが、なぜここで `Not Found` になるのかが不明です。

![スクリーンショット 2019-04-17 22 17 18](https://user-images.githubusercontent.com/17425060/56291791-e350f880-6160-11e9-9649-c1a41f0e4548.png)

Request先がおかしいのかなと思っております。 `/app/views/devise/passwords/edit` 

Railsチュートリアルを見たのですが、そこではメソッドを再設定したりしているのですが、Deviseを使っているのにそこまでするつ必要があるのかなという思っております。
https://railstutorial.jp/chapters/account_activation_password_reset?version=4.2#sec-password_resets_controller_and_form

また他のサイトでは、カスタマイズもありますが、なんか違うなと思います。
https://easyramble.com/customize-mail-template-of-devise.html

ご教示いただけませんでしょうか？
よろしくお願いいたします。

**Comment by konchanxxx** [comment]
@sumura80 
request URLなのでまずは `rake routes` で該当しているルーティングが定義されているか確認してみるのが先かなと思います:bow:

**Comment by sumura80** [comment]
@rexitorg 

`rake routes` を確認したところルーティングは定義されております。Deviseを使用しているので、こちらは自動で作成されている様です。

![user_pass_edit](https://user-images.githubusercontent.com/17425060/56843175-546a7b80-68d8-11e9-9ec9-a3169ce3cfa3.png)

**Comment by sumura80** [comment]
@rexitorg 
こちら解決しましたので、クローズさせていただきます。
ありがとうございました。

**Comment by konchanxxx** [comment]
おお良かったです。原因はなんだったか可能であれば記載をお願いします。
パスワード再設定メールに記載するURLをフルパスにする必要があったとかでしょうか？

**Comment by sumura80** [comment]
原因は、productionの環境設定で、自分のドメインを設定していないことが原因でした。:sweat:
`config.action_mailer.default_url_options = { host: '自分で取得したドメイン' } `
しかも自分の場合 `www` も記述していなかったので、エラーが出ておりました。
