### ISSUE TITLE
heroku create 時にエラー

### ISSUE THREAD

**Issue by yuumasakura777** [rexitorg/menta#74]
## 概要
herokuでデプロイ作業をしていたのですが、エラーが出てしまい、そこから進めなくなりました。

## 実現したいこと
エラーを解決したい。

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
create heroku アプリ名　を実行した時に次のようなエラが起こりherokuのurlが出てこない。

Name must start with a letter, end with a letter or digit and can only
contain lowercase letters, digits, and dashes.

## 解決するために行ったこと
コマンドの見直し、herokuのアプリの確認(無料枠は5つしかアプリを公開できないため)

## 問題となっている箇所の予想
git initをした時(master)が出ないのでそこが原因かと思います。

**Comment by konchanxxx** [comment]
@yuumasakura777 

> Name must start with a letter, end with a letter or digit and can only
contain lowercase letters, digits, and dashes.

このエラーメッセージはどう解釈している感じでしょうか？

**Comment by yuumasakura777** [comment]
自己解決できました。
ありがとうございました。
