### ISSUE TITLE
Heroku上で画像とコメントが登録できない。

### ISSUE THREAD

**Issue by sumura80** [rexitorg/menta#75]
## 概要
現在作成しているアプリで、画像を追加できる機能を実装中。
こちらはローカル環境で問題なく機能しています。
これがHeroku上だと画像とコメントの登録ができません。

## 実現したいこと
Heroku上でも登録できるようにしたい。

## 困っていること
heroku run rails consoleで確認すると、画像が登録できてないことが

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
```` 
irb(main):003:0> @extra = Extraimg.last
  Extraimg Load (0.9ms)  SELECT  "extraimgs".* FROM "extraimgs" ORDER BY "extraimgs"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> nil
````

以前から何度もHerokuへデプロイしておりますが、この機能だけ追加されません。
今回どうしてもわからず質問させていただきます。
ご教示頂ければ幸いです。よろしくお願いいたします。:bow:

**Comment by soipon05** [comment]
画像の保存先ってっどこになっています？
S3だとS3の設定がうまくいっていなくてデプロイしたら保存できてるように見えてできてなかったってことは自分経験あります！

**Comment by sumura80** [comment]
soipon005さん、お返事ありがとうございます。
画像の保存先はS3です。通常の画像はS3で投稿できております。
ある一部の画像とコメント機能だけ機能しないので、S3というよりコードに問題がありそうです。

**Comment by soipon05** [comment]
そうなると自分ではまだわからないです。
Extraimg.last => nil
になっているってことはDB自体に保存できていないということなのかなと思ったんですけどローカルでは保存できてそうなので自分もこの事象気になります。
お力になれずすみません。

**Comment by sumura80** [comment]
soipon05さん
お忙しい中ご連絡ありがとうございました。
問題が解決次第共有できればと思います！ご丁寧にお返事いただけて嬉しかったです。:smile:

**Comment by konchanxxx** [comment]
@sumura80 
GitHubの添付をお願いします:bow:

**Comment by sumura80** [comment]
@rexitorg 
こちらの機能ですが、昨日まで機能しなかったのですが他の機能を実装するためにpushしていたら、急に登録できるようになりました。なんか腑に落ちませんがとりあえず機能したので、質問を終わらせていただきます。
ありがとうございました。

**Comment by konchanxxx** [comment]
機能したなら良かったのですが、なんとなく動く状態は避けるべきなので、Git,GitHubで差分を厳密に管理するようにした方が良いと思いました:bow:
