### ISSUE TITLE
削除ボタンを押した時、uninitialized constant Post::Linkというエラーが発生する

### ISSUE THREAD

**Issue by yuumasakura777** [rexitorg/menta#76]
## 概要
投稿機能アプリで投稿削除する機能を作っていたのですが、ある時から削除ボタンを押した時、uninitialized constant というエラーが発生するようになりました。

## 実現したいこと
uninitialized constant Post::Linkを取り除き、削除ボタンを押した時、削除できるようにしたいです。

## 困っていること
削除ボタンを押した時、uninitialized constant Post::Linkというエラーが発生する。

## 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。
Completed 500 Internal Server Error 
NameError (uninitialized constant Post::Link):

## 解決するために行ったこと
コントローラー、ビューでの誤字の確認、
show.html.erbでの削除ボタンへのリンクのurl、引数の確認

## 問題となっている箇所の予想
削除ボタンを押した時の処理で、rollback transactionと出るのでこれが原因かと思っています。

## 問題となっているアプリケーションのGitHub URL
https://github.com/yuumasakura777/posted_function

**Comment by konchanxxx** [comment]
確認します:bow:

**Comment by konchanxxx** [comment]
@yuumasakura777 

https://github.com/yuumasakura777/posted_function/blob/master/app/models/post.rb#L5

これが

```rb
has_many :likes, dependent: :destroy
```

ですかね。linksにtypoしているのでdestroy（削除処理）するときにlinks => Linkにモデル名を変換してしまってエラーになっている気がしますmm

**Comment by yuumasakura777** [comment]
仰る通り、has_many :likes, dependent: :destroyを削除すると動きました。
ありがとうございます!
