### ISSUE TITLE
画像ファイルを指定する時の書き方（絶対・相対パス）

### ISSUE THREAD

**Issue by mamechan21** [rexitorg/menta#9]
# 概要
AWSのCloud9でrailsを使ってアプリを作る練習をしています。以前画像ファイルの位置を指定する時に絶対パスと相対パスについて習いました。どうやらAWSは他のと違うみたいで、以下のように書くようです。
・ home.htmi.erbに、imagesディレクトリ内のchild.jpegという画像ファイルを表示したい時。

＜img src="assets/child.jpeg" width="500" height="300"＞　と書く。

これはわかったので問題ないのですが、これは以前習った絶対パス、相対パスの書き方とは違う気がします。
![aws](https://user-images.githubusercontent.com/40751874/51361401-f842cf00-1b12-11e9-98dc-062043f22961.JPG)

# 実現したいこと
もし、これが一般的な書き方だと、以下のようになると思うですが以前習ったときの記憶が遠くて自信がないので確認をお願いします。

絶対パス
app/assets/images/child.jpeg

相対パス（２階層上であってますか？？？）
../../images/child.jpeg

# 困っていること
困っているというか知りたい、確認したいのは・・・
１．この場合、AWSは他と書き方が違うのか？
２．絶対パス、相対パスの階層の数え方がイマイチわからない。

# 困っていることがバグの場合は事象やログ、エラーメッセージをできるだけそのまま（抜粋などしない）下記に記載してください。

# 解決するために行ったこと

# 問題となっている箇所の予想

よろしくお願いします。

**Comment by rexitorg** [comment]
> ＜img src="assets/child.jpeg" width="500" height="300"＞　と書く。

erbを利用するならまず生のimgタグを記述するのが良くないですね
assets配下に配置したファイルならimage_tagを利用するのが良いというか必須だと思います。
http://tech-log.hatenablog.jp/entry/2015/12/30/173953


> １．この場合、AWSは他と書き方が違うのか？

AWS固有の問題ではないと思います。

> もし、これが一般的な書き方だと、以下のようになると思うですが以前習ったときの記憶が遠くて自信がないので確認をお願いします。

うーん、どういう教科書なのかわからない（自分がその教科書を持っていないので記述内容が正しいかどうかわからない..）ですが、前述した通りRailsだとimage_tagを使うのが正しいと思います。

> 相対パス（２階層上であってますか？？？）
../../images/child.jpeg

これは `./../../assets/images/child.png` とかな気がしますね。assetsが抜けていそうです。viewファイルからの相対パスなので。

> ２．絶対パス、相対パスの階層の数え方がイマイチわからない。

あーターミナルで `ls` コマンドとかを使ってみるとわかるようになるかもです。
```
ls .
```
とかすると現在のカレントディレクトの情報が出るので

```
ls ./..
```
で一階層上をみてみるとかしていくとどういう階層にいるかわかるかなと思います:bow:

**Comment by rexitorg** [comment]
あと基礎的なRubyのことが記述されている下記の書籍を購入して学習して頂きたいです:bow:
https://www.amazon.co.jp/dp/B077Q8BXHC/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1

**Comment by mamechan21** [comment]
ご解答ありがとうございます。
image_tag、、、そういえば前に習いました。勉強しなおしですね。

オススメしていただいた本なのです、現在以下の２冊ももっています。これらの本よりも教えていただいた本の方がよろしいでしょうか。

https://amzn.to/2RT0kUq

https://amzn.to/2sBqQmU

パスの件、ls. で一度みてみます！

**Comment by rexitorg** [comment]
👍 

> オススメしていただいた本なのです、現在以下の２冊ももっています。これらの本よりも教えていただいた本の方がよろしいでしょうか。

こちらの2冊読んだことないのですが、自分がオススメしている本はRuby on Railsではなく、Rubyについて学ぶ本なので読んだ方が良いと思います。
Ruby on RailsはWAF(Web Application Framework)と呼ばれるものでアプリを作るのを簡単にしてくれるツールではあるのですが、基盤はRubyでできているのでRubyの基礎ができていないと応用が効かないのです:cry: Rubyができる人がRoRを使って初めてアプリケーションを簡単に作れることができるようになるんです。そのためRubyの基礎を学ぶという意味でもおすすめさせて頂いた書籍を読むのが良いかなと思います:bow:

**Comment by rexitorg** [comment]
こちらimage_tagについては再学習されるということで一旦解決したと思いますのでcloseしておきます:bow:

**Comment by mamechan21** [comment]
Close、わかりました。
あと、お勧めいただいた本も取り寄せてみます。
